### ISSUE TITLE
voice widget test issue(lex)

### ISSUE THREAD

**Issue by dragonflymxj** [awslabs/aws-sdk-android-samples#106]
I met below issue when test voice widget,who can give me a help?

I/System.out: debugger has settled (1333)
W/art: JIT profile information will not be recorded: profile file does not exits.
I/MultiDex: VM with version 2.1.0 has multidex support
I/MultiDex: install
I/MultiDex: VM has multidex support, MultiDex support library is disabled.
I/HwCust: Constructor found for class android.app.HwCustActivityImpl
I/HwCust: Constructor found for class android.app.HwCustHwWallpaperManagerImpl
E/MainActivity: Initializing app
I/HwPointEventFilter: support AFT
I/OpenGLRenderer: Initialized EGL, version 1.4
W/linker: /vendor/lib/libhwuibp.so: unused DT entry: type 0xf arg 0xeb5
W/art: Class com.amazonaws.AmazonWebServiceClient failed lock verification and will run slower.
W/art: Common causes for lock verification issues are non-optimized dex code
W/art: and incorrect proguard optimizations.
W/art: Class com.amazonaws.auth.AbstractAWSSigner failed lock verification and will run slower.
I/HwPointEventFilter: support AFT
I/art: Do partial code cache collection, code=31KB, data=30KB
I/art: After code cache collection, code=30KB, data=30KB
I/art: Increasing code cache capacity to 128KB
E/AudioRecord: AudioFlinger could not create record track, status: -1
E/AudioRecord-JNI: Error creating AudioRecord instance: initialization check failed with status -1.
E/android.media.AudioRecord: Error code -20 when initializing native AudioRecord object.
E/Lex: InteractiveVoiceViewAdapter: Interaction error
       java.lang.SecurityException: Insufficient permissions to start ASR.
           at com.amazonaws.mobileconnectors.lex.interactionkit.internal.audio.AudioRecorder.checkRecordingPermission(AudioRecorder.java:192)
           at com.amazonaws.mobileconnectors.lex.interactionkit.internal.audio.AudioRecorder.<init>(AudioRecorder.java:181)
           at com.amazonaws.mobileconnectors.lex.interactionkit.internal.audio.AudioRecorder.<init>(AudioRecorder.java:121)
           at com.amazonaws.mobileconnectors.lex.interactionkit.internal.audio.LexAudioRecorder.<init>(LexAudioRecorder.java:137)
           at com.amazonaws.mobileconnectors.lex.interactionkit.internal.audio.LexAudioRecorder.<init>(LexAudioRecorder.java:112)
           at com.amazonaws.mobileconnectors.lex.interactionkit.internal.audio.LexAudioRecorderBuilder.build(LexAudioRecorderBuilder.java:128)
           at com.amazonaws.mobileconnectors.lex.interactionkit.InteractionClient$1.run(InteractionClient.java:317)
           at java.lang.Thread.run(Thread.java:776)
E/VoiceActivity: Error: Error from Bot
                 java.lang.SecurityException: Insufficient permissions to start ASR.
                     at com.amazonaws.mobileconnectors.lex.interactionkit.internal.audio.AudioRecorder.checkRecordingPermission(AudioRecorder.java:192)
                     at com.amazonaws.mobileconnectors.lex.interactionkit.internal.audio.AudioRecorder.<init>(AudioRecorder.java:181)
                     at com.amazonaws.mobileconnectors.lex.interactionkit.internal.audio.AudioRecorder.<init>(AudioRecorder.java:121)
                     at com.amazonaws.mobileconnectors.lex.interactionkit.internal.audio.LexAudioRecorder.<init>(LexAudioRecorder.java:137)
                     at com.amazonaws.mobileconnectors.lex.interactionkit.internal.audio.LexAudioRecorder.<init>(LexAudioRecorder.java:112)
                     at com.amazonaws.mobileconnectors.lex.interactionkit.internal.audio.LexAudioRecorderBuilder.build(LexAudioRecorderBuilder.java:128)
                     at com.amazonaws.mobileconnectors.lex.interactionkit.InteractionClient$1.run(InteractionClient.java:317)
                     at java.lang.Thread.run(Thread.java:776)

**Comment by karthiksaligrama** [comment]
You are missing permissions for recording audio. 
If you have already included the permissions in the android manifest then you might have to go to applications -> permissions and enable microphone permissions
