### ISSUE TITLE
S3TransferUtilitySample Not Working!

### ISSUE THREAD

**Issue by ZaidWaseem10** [awslabs/aws-sdk-android-samples#113]
Hello! I thoroughly went through the readme file, but still I can't download or upload a file! When I tap the download button the app force closes! And When I try to upload a file - it fails. 
Kindly help me out.
![image](https://cloud.githubusercontent.com/assets/20317678/24205159/69f5425c-0f3c-11e7-9ec8-a00cfca4d084.png)

**Comment by mlshon** [comment]
Hi,
Could you provide a stacktrace for me as I am unable to reproduce the problem you're having?

**Comment by ZaidWaseem10** [comment]
These are the errors that I get when I try to upload a file 
![image](https://cloud.githubusercontent.com/assets/20317678/24213301/d4e8cda6-0f53-11e7-93c3-c9fd32912a2b.png)

**Comment by ZaidWaseem10** [comment]
**Errors that I get when I tap the download button**

03-22 23:05:03.438 10964-11055/com.amazonaws.demo.s3transferutility E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
                                                                                      Process: com.amazonaws.demo.s3transferutility, PID: 10964
                                                                                      Theme: themes:{default=overlay:jahirfiquitiva.themes.meliornui, iconPack:com.zavukodlak.candycons, fontPkg:jahirfiquitiva.themes.meliornui, com.android.systemui=overlay:jahirfiquitiva.themes.meliornui, com.android.systemui.navbar=overlay:jahirfiquitiva.themes.meliornui}
                                                                                      java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                                                          at android.os.AsyncTask$3.done(AsyncTask.java:309)
                                                                                          at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                                                                                          at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                                                                                          at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                          at java.lang.Thread.run(Thread.java:818)
                                                                                       Caused by: com.amazonaws.services.cognitoidentity.model.ResourceNotFoundException: IdentityPool 'us-west-2:52a1dc34-e79e-404c-aa37-ff9c0befe3f0' not found. (Service: AmazonCognitoIdentity; Status Code: 400; Error Code: ResourceNotFoundException; Request ID: 120cefc5-0f2a-11e7-9cf3-3f87fde4c09a)
                                                                                          at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:712)
                                                                                          at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:388)
                                                                                          at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:199)
                                                                                          at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.invoke(AmazonCognitoIdentityClient.java:558)
                                                                                          at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.getId(AmazonCognitoIdentityClient.java:444)
                                                                                          at com.amazonaws.auth.AWSAbstractCognitoIdentityProvider.getIdentityId(AWSAbstractCognitoIdentityProvider.java:172)
                                                                                          at com.amazonaws.auth.AWSEnhancedCognitoIdentityProvider.refresh(AWSEnhancedCognitoIdentityProvider.java:76)
                                                                                          at com.amazonaws.auth.CognitoCredentialsProvider.retryRefresh(CognitoCredentialsProvider.java:597)
                                                                                          at com.amazonaws.auth.CognitoCredentialsProvider.startSession(CognitoCredentialsProvider.java:565)
                                                                                          at com.amazonaws.auth.CognitoCredentialsProvider.getCredentials(CognitoCredentialsProvider.java:371)
                                                                                          at com.amazonaws.auth.CognitoCachingCredentialsProvider.getCredentials(CognitoCachingCredentialsProvider.java:441)
                                                                                          at com.amazonaws.auth.CognitoCachingCredentialsProvider.getCredentials(CognitoCachingCredentialsProvider.java:76)
                                                                                          at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4369)
                                                                                          at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4332)
                                                                                          at com.amazonaws.services.s3.AmazonS3Client.listObjects(AmazonS3Client.java:680)
                                                                                          at com.amazonaws.services.s3.AmazonS3Client.listObjects(AmazonS3Client.java:640)
                                                                                          at com.amazonaws.demo.s3transferutility.DownloadSelectionActivity$GetFileListTask.doInBackground(DownloadSelectionActivity.java:125)
                                                                                          at com.amazonaws.demo.s3transferutility.DownloadSelectionActivity$GetFileListTask.doInBackground(DownloadSelectionActivity.java:109)
                                                                                          at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                                                          at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                                          at java.lang.Thread.run(Thread.java:818) 
03-22 23:05:03.846 10964-10964/com.amazonaws.demo.s3transferutility E/WindowManager: android.view.WindowLeaked: Activity com.amazonaws.demo.s3transferutility.DownloadSelectionActivity has leaked window com.android.internal.policy.PhoneWindow$DecorView{3eaec2a V.E...... R.....ID 0,0-513,526} that was originally added here
                                                                                         at android.view.ViewRootImpl.<init>(ViewRootImpl.java:372)
                                                                                         at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:299)
                                                                                         at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:86)
                                                                                         at android.app.Dialog.show(Dialog.java:319)
                                                                                         at android.app.ProgressDialog.show(ProgressDialog.java:116)
                                                                                         at android.app.ProgressDialog.show(ProgressDialog.java:99)
                                                                                         at android.app.ProgressDialog.show(ProgressDialog.java:94)
                                                                                         at com.amazonaws.demo.s3transferutility.DownloadSelectionActivity$GetFileListTask.onPreExecute(DownloadSelectionActivity.java:117)
                                                                                         at android.os.AsyncTask.executeOnExecutor(AsyncTask.java:604)
                                                                                         at android.os.AsyncTask.execute(AsyncTask.java:551)
                                                                                         at com.amazonaws.demo.s3transferutility.DownloadSelectionActivity.onResume(DownloadSelectionActivity.java:60)
                                                                                         at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1259)
                                                                                         at android.app.Activity.performResume(Activity.java:6327)
                                                                                         at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3126)
                                                                                         at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3168)
                                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2515)
                                                                                         at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363)
                                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                         at android.os.Looper.loop(Looper.java:148)
                                                                                         at android.app.ActivityThread.main(ActivityThread.java:5461)
                                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

![image](https://cloud.githubusercontent.com/assets/20317678/24213603/e3e1a584-0f54-11e7-829c-d2eb18ad514c.png)

**Comment by mlshon** [comment]
Thank you.

Looks like our sample app hardcodes using US_EAST_1 region. We will work on updating our sample app!
In the meanwhile, you can unblock yourself by navigating to the Util.java class to line 56.
Change the Regions.US_EAST_1 to Regions.US_WEST_2 (whichever region your identity pool belongs to).

Please reopen this if there are more issues.

**Comment by ZaidWaseem10** [comment]
Thanks for your time! My issue has been resolved!
