### ISSUE TITLE
AmazonCognitoAuthDemo: Sign In Fails with FileNotFoundException When App Client Requires Secret

### ISSUE THREAD

**Issue by kyarosh** [awslabs/aws-sdk-android-samples#145]
When an app client for a User Pool requires a client secret, the AmazonCognitoAuthDemo will fail to properly complete the auth process, resulting in an exception to be returned to the callback defined in MainActivity. The exception has a stacktrace similar to the following:

```
java.io.FileNotFoundException: https://AUTH_DOMAIN.auth.REGION.amazoncognito.com/token
   at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:250)
   at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
   at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java)
   at com.amazonaws.mobileconnectors.cognitoauth.util.AuthHttpClient.httpPost(AuthHttpClient.java:82)
   at com.amazonaws.mobileconnectors.cognitoauth.AuthClient$1.run(AuthClient.java:288)
   at java.lang.Thread.run(Thread.java:761)
```

This occurs because, even though "cognito_client_secret" can be defined in strings.xml, it is never referenced in the code. As a result, when the application makes a request to the [/token](http://docs.aws.amazon.com/cognito/latest/developerguide/token-endpoint.html) endpoint to exchange an auth code for tokens, the endpoint responds with 400 Bad Request and returns an "invalid_client" error. The subsequent call to HttpsURLConnection.getInputStream() in the aws-android-sdk-cognitoauth then throws a FileNotFoundException when it calls getInputStream(). (The actual body of the response needs to be retrieved with getErrorStream().)

**Comment by patvyas** [comment]
Thank you for reporting this. We will try to reproduce internally and then confirm it as bug.
