### ISSUE TITLE
Lex Sample : Audio playback failed

### ISSUE THREAD

**Issue by nikeshbhawsar** [awslabs/aws-sdk-android-samples#148]
Hi,
I have configured Lex Sample to use with android app. I am able to invoke my Intent. But in response it is failing while playing the audio. I am getting below error:

**com.amazonaws.sample.lex E/Lex: InteractiveVoiceViewAdapter: Audio playback failed**
com.amazonaws.mobileconnectors.lex.interactionkit.exceptions.LexClientException: Audio playback failed
at com.amazonaws.mobileconnectors.lex.interactionkit.InteractionClient$7.run(InteractionClient.java:542)
at android.os.Handler.handleCallback(Handler.java:615)
at android.os.Handler.dispatchMessage(Handler.java:92)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:4947)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1038)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:805)
at dalvik.system.NativeStart.main(Native Method)
**Caused by: java.io.IOException: setDataSourceFD failed.: status=0x80000000**
at android.media.MediaPlayer.setDataSource(Native Method)
at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1186)
at com.amazonaws.mobileconnectors.lex.interactionkit.InteractionClient.processResponseAudioPlayback(InteractionClient.java:533)
at com.amazonaws.mobileconnectors.lex.interactionkit.InteractionClient.access$1200(InteractionClient.java:79)
at com.amazonaws.mobileconnectors.lex.interactionkit.InteractionClient$2.run(InteractionClient.java:376)
at java.lang.Thread.run(Thread.java:856)

**Comment by rohandubal** [comment]
Hi, could you provide some code snippet by which we can reproduce this?
