### ISSUE TITLE
Polly client not being initialized when used in the Lex Sample

### ISSUE THREAD

**Issue by jinot92** [awslabs/aws-sdk-android-samples#155]
Hi,
I am trying to integrate Polly in the Lex sample.
I am facing issues during the initialisation of the polly client
```javascript
private void initializeLexSDK() {
        Log.d(TAG, "Lex Client");
        // Cognito Identity Broker is the credentials provider.
        CognitoCredentialsProvider credentialsProviderLex = new CognitoCredentialsProvider(
                appContext.getResources().getString(R.string.identity_id_test),
                Regions.fromName("us-east-1"));

        // Create Lex interaction client.
        lexInteractionClient = new InteractionClient(getApplicationContext(),
                credentialsProviderLex,
                Regions.US_EAST_1,
                appContext.getResources().getString(R.string.bot_name),
                appContext.getResources().getString(R.string.bot_alias));
        lexInteractionClient.setAudioPlaybackListener(audioPlaybackListener);
        lexInteractionClient.setInteractionListener(interactionListener);
    }
    void initPollyClient() {
        // Initialize the Amazon Cognito credentials provider.
        ClientConfiguration cf = new ClientConfiguration();
        cf.setSignerOverride("QueryStringSignerType");

        credentialsProviderPolly = new CognitoCachingCredentialsProvider(
                appContext,
                appContext.getResources().getString(R.string.identity_id_test),
                MY_REGION
        );

        // Create a client that supports generation of presigned URLs.
        client = new AmazonPollyPresigningClient(credentialsProviderPolly);
    }
```
On which I am getting the following error

```
FATAL EXCEPTION: main
Process: com.amazonaws.sample.lex, PID: 21981
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.amazonaws.sample.lex/com.amazonaws.sample.lex.TextActivity}: java.lang.IllegalArgumentException
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2659)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2724)
at android.app.ActivityThread.-wrap12(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1473)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6123)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
Caused by: java.lang.IllegalArgumentException
at com.amazonaws.auth.SignerFactory.createSigner(SignerFactory.java:115)
at com.amazonaws.auth.SignerFactory.lookupAndCreateSigner(SignerFactory.java:104)
at com.amazonaws.auth.SignerFactory.getSigner(SignerFactory.java:79)
at com.amazonaws.AmazonWebServiceClient.computeSignerByServiceRegion(AmazonWebServiceClient.java:379)
at com.amazonaws.AmazonWebServiceClient.computeSignerByURI(AmazonWebServiceClient.java:351)
at com.amazonaws.AmazonWebServiceClient.setEndpoint(AmazonWebServiceClient.java:215)
at com.amazonaws.services.polly.AmazonPollyClient.init(AmazonPollyClient.java:281)
at com.amazonaws.services.polly.AmazonPollyClient.<init>(AmazonPollyClient.java:261)
at com.amazonaws.services.polly.AmazonPollyPresigningClient.<init>(AmazonPollyPresigningClient.java:128)
at com.amazonaws.services.polly.AmazonPollyPresigningClient.<init>(AmazonPollyPresigningClient.java:107)
at com.amazonaws.services.polly.AmazonPollyPresigningClient.<init>(AmazonPollyPresigningClient.java:76)
at com.amazonaws.sample.lex.TextActivity.initPollyClient(TextActivity.java:177)
at com.amazonaws.sample.lex.TextActivity.init(TextActivity.java:141)
at com.amazonaws.sample.lex.TextActivity.onCreate(TextActivity.java:103)
at android.app.Activity.performCreate(Activity.java:6672)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1140)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2612)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2724) 
at android.app.ActivityThread.-wrap12(ActivityThread.java) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1473) 
at android.os.Handler.dispatchMessage(Handler.java:102) 
at android.os.Looper.loop(Looper.java:154) 
at android.app.ActivityThread.main(ActivityThread.java:6123) 
at java.lang.reflect.Method.invoke(Native Method) 
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757) 
```

**Comment by PikkaPikkachu** [comment]
I am having the same problem! Did you find any solutions yet?

**Comment by kredden** [comment]
Hi, we'll need to get some more info to be able to help you out.

What version of the SDK are you using?  I just tried adding this code to the Lex sample and it is not having any problems calling it.

What is your "MY_REGION" set to in initPollyClient?  There are a couple minor changes I made to the code above to ensure that the same values were being used for the regions:

    private void initializeLexSDK() {
        Log.d(TAG, "Lex Client");
        // Cognito Identity Broker is the credentials provider.
        CognitoCredentialsProvider credentialsProvider = new CognitoCredentialsProvider(
                appContext.getResources().getString(R.string.identity_id_test),
                Regions.fromName(appContext.getResources().getString(R.string.aws_region)));

        // Create Lex interaction client.
        lexInteractionClient = new InteractionClient(getApplicationContext(),
                credentialsProvider,
                Regions.US_EAST_1,
                appContext.getResources().getString(R.string.bot_name),
                appContext.getResources().getString(R.string.bot_alias));
        lexInteractionClient.setAudioPlaybackListener(audioPlaybackListener);
        lexInteractionClient.setInteractionListener(interactionListener);
    }

    void initPollyClient() {
        // Initialize the Amazon Cognito credentials provider.
        ClientConfiguration cf = new ClientConfiguration();
        cf.setSignerOverride("QueryStringSignerType");

        CognitoCachingCredentialsProvider credentialsProvider = new CognitoCachingCredentialsProvider(
                getApplicationContext(),
                appContext.getResources().getString(R.string.identity_id_test),
                Regions.fromName(appContext.getResources().getString(R.string.aws_region))
        );

        // Create a client that supports generation of presigned URLs.
        pollyClient = new AmazonPollyPresigningClient(credentialsProvider);
    }

Regards,
Kevin

**Comment by kredden** [comment]
Were you able to get it working?

Regards,
Kevin

**Comment by PikkaPikkachu** [comment]
Yes, the sdk version was outdated and causing trouble. Please update it in the lex polly sample app. 
Thanks and regards,
Prakriti

**Comment by kredden** [comment]
That was done last week.
