### ISSUE TITLE
ResourceNotFoundException this happens randomly.

### ISSUE THREAD

**Issue by rakshitsoni** [awslabs/aws-sdk-android-samples#163]
```
E/FindMeCameraActivity: Error during upload: 33
                                                                             com.amazonaws.services.cognitoidentity.model.ResourceNotFoundException: IdentityPool 'us-east-1:8d8f7658-417e-46dd-a884-8b5cf9165a02' not found. (Service: AmazonCognitoIdentity; Status Code: 400; Error Code: ResourceNotFoundException; Request ID: 03003761-c756-11e7-94f5-912865a69aad)
                                                                                 at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:729)
                                                                                 at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:405)
                                                                                 at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:212)
                                                                                 at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.invoke(AmazonCognitoIdentityClient.java:559)
                                                                                 at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.getId(AmazonCognitoIdentityClient.java:445)
                                                                                 at com.amazonaws.auth.AWSAbstractCognitoIdentityProvider.getIdentityId(AWSAbstractCognitoIdentityProvider.java:172)
                                                                                 at com.amazonaws.auth.AWSEnhancedCognitoIdentityProvider.refresh(AWSEnhancedCognitoIdentityProvider.java:76)
                                                                                 at com.amazonaws.auth.CognitoCredentialsProvider.retryRefresh(CognitoCredentialsProvider.java:694)
                                                                                 at com.amazonaws.auth.CognitoCredentialsProvider.startSession(CognitoCredentialsProvider.java:662)
                                                                                 at com.amazonaws.auth.CognitoCredentialsProvider.getCredentials(CognitoCredentialsProvider.java:445)
                                                                                 at com.amazonaws.auth.CognitoCachingCredentialsProvider.getCredentials(CognitoCachingCredentialsProvider.java:485)
                                                                                 at com.amazonaws.auth.CognitoCachingCredentialsProvider.getCredentials(CognitoCachingCredentialsProvider.java:77)
                                                                                 at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4637)
                                                                                 at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1747)
                                                                                 at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.uploadSinglePartAndWaitForCompletion(UploadTask.java:214)
                                                                                 at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:88)
                                                                                 at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:47)
                                                                                 at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                 at java.lang.Thread.run(Thread.java:818)
```

**Comment by kvasukib** [comment]
Hello @rakshitsoni,

Can you verify if your region is us-east-1?
