### ISSUE TITLE
S3TransferUtilitySample EACCES (Permission denied)

### ISSUE THREAD

**Issue by uc3po** [awslabs/aws-sdk-android-samples#171]
Hi, i got this exception when i'm testing. Did you try it 

using:
amazonaws:aws-android-sdk-s3:2.6.+
android 6

com.amazonaws.AmazonClientException: Unable to store object contents to disk: /storage/emulated/0/005D4115-300C-488A-B62F-00411560248C.m4a: open failed: EACCES (Permission denied)
                                                                                            at com.amazonaws.mobileconnectors.s3.transferutility.DownloadTask.saveToFile(DownloadTask.java:161)
                                                                                            at com.amazonaws.mobileconnectors.s3.transferutility.DownloadTask.call(DownloadTask.java:107)
                                                                                            at com.amazonaws.mobileconnectors.s3.transferutility.DownloadTask.call(DownloadTask.java:42)
                                                                                            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                            at java.lang.Thread.run(Thread.java:818)
                                                                                         Caused by: java.io.FileNotFoundException: /storage/emulated/0/005D4115-300C-488A-B62F-00411560248C.m4a: open failed: EACCES (Permission denied)
                                                                                            at libcore.io.IoBridge.open(IoBridge.java:452)
                                                                                            at java.io.FileOutputStream.<init>(FileOutputStream.java:87)
                                                                                            at com.amazonaws.mobileconnectors.s3.transferutility.DownloadTask.saveToFile(DownloadTask.java:148)
                                                                                            at com.amazonaws.mobileconnectors.s3.transferutility.DownloadTask.call(DownloadTask.java:107) 
                                                                                            at com.amazonaws.mobileconnectors.s3.transferutility.DownloadTask.call(DownloadTask.java:42) 
                                                                                            at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                                            at java.lang.Thread.run(Thread.java:818) 
                                                                                         Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
                                                                                            at libcore.io.Posix.open(Native Method)
                                                                                            at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
                                                                                            at libcore.io.IoBridge.open(IoBridge.java:438)

**Comment by minbi** [comment]
Hi @uc3po ,

If the device you are testing on does not have external storage, then the sample may crash because it writes to external storage for downloads.

You may change the location that the files are being downloaded to at this location in the sample app. https://github.com/awslabs/aws-sdk-android-samples/blob/master/S3TransferUtilitySample/src/com/amazonaws/demo/s3transferutility/DownloadActivity.java#L340

We will update this thread when we can upload a fix.

**Comment by uc3po** [comment]
I changed Main Activity. Ask&Check run time permission like this code and solved it. 
( Android API level > 23). 
Thanks.


       private static final int REQUEST_EXTERNAL_STORAGE = 1;
       private static String[] PERMISSIONS_STORAGE = {
            Manifest.permission.READ_EXTERNAL_STORAGE,
            Manifest.permission.WRITE_EXTERNAL_STORAGE
       };

       public static void verifyStoragePermissions(Activity activity) {
        // Check if we have write permission
        int permission = ActivityCompat.checkSelfPermission(activity,  Manifest.permission.WRITE_EXTERNAL_STORAGE);

        if (permission != PackageManager.PERMISSION_GRANTED) {
            // We don't have permission so prompt the user
            ActivityCompat.requestPermissions(
                    activity,
                    PERMISSIONS_STORAGE,
                    REQUEST_EXTERNAL_STORAGE
            );
        }
    }
