### ISSUE TITLE
kinesisVideoStreamParseFragmentAck

### ISSUE THREAD

**Issue by suryakant-t-yadav** [awslabs/aws-sdk-android-samples#183]
while trying to implement AmazonKinesisVideoDemoApp it gives error when I start streaming
first i get error as 
E/ACodec: [OMX.qcom.video.encoder.avc] storeMetaDataInBuffers (output) failed w/ err -1010

and after that.

E/platform-utils: kinesisVideoStreamParseFragmentAck(): Failed to parse a fragment ack with status code 0x52000047
E/KinesisVideoAndroidClient: 2018-01-18T12:36Z T3679: EXCEPTION: ProducerException: Processing ACK threw an exception. Logging and continuing. : Failed to parse a fragment ack.

and after that I get error as 

error updating sink with frame
                                                                                              com.amazonaws.kinesisvideo.producer.ProducerException: Failed to put a frame into the stream.
                                                                                                  at com.amazonaws.kinesisvideo.producer.jni.NativeKinesisVideoProducerJni.putKinesisVideoFrame(Native Method)
                                                                                                  at com.amazonaws.kinesisvideo.producer.jni.NativeKinesisVideoProducerJni.putFrame(NativeKinesisVideoProducerJni.java:448)
                                                                                                  at com.amazonaws.kinesisvideo.producer.jni.NativeKinesisVideoProducerStream.putFrame(NativeKinesisVideoProducerStream.java:230)
                                                                                                  at com.amazonaws.kinesisvideo.mediasource.ProducerStreamSink.onFrame(ProducerStreamSink.java:52)
                                                                                                  at com.amazonaws.mobileconnectors.kinesisvideo.mediasource.android.AndroidCameraMediaSource$2.onFrameAvailable(AndroidCameraMediaSource.java:198)
                                                                                                  at com.amazonaws.mobileconnectors.kinesisvideo.encoding.EncoderWrapper.sendEncodedFrameToProducerSDK(EncoderWrapper.java:198)
                                                                                                  at com.amazonaws.mobileconnectors.kinesisvideo.encoding.EncoderWrapper.processEncodedData(EncoderWrapper.java:164)
                                                                                                  at com.amazonaws.mobileconnectors.kinesisvideo.encoding.EncoderWrapper.processEncoderOutputBuffer(EncoderWrapper.java:145)
                                                                                                  at com.amazonaws.mobileconnectors.kinesisvideo.encoding.EncoderWrapper.getDataFromEncoder(EncoderWrapper.java:121)
                                                                                                  at com.amazonaws.mobileconnectors.kinesisvideo.encoding.EncoderWrapper.encodeFrame(EncoderWrapper.java:94)
                                                                                                  at com.amazonaws.mobileconnectors.kinesisvideo.camera.CameraFramesSource$1.onImageAvailable(CameraFramesSource.java:68)
                                                                                                  at android.media.ImageReader$ListenerHandler.handleMessage(ImageReader.java:648)
                                                                                                  at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                  at android.os.Looper.loop(Looper.java:148)
                                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5443)
                                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
                                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)

has anyone face the same issue..
any solution please help..
thanks in advance...

**Comment by MushMal** [comment]
@suryakant-t-yadav, as @minbi mentioned, could you please provide a little more information.

* Device make/model
* Software version
* Is the error happening immediately upon the stream starting?
* Could you please include more of the system logs (which might include some video driver output)?

You seem to have two issues. The first is that the SDK fails to parse the ACKs - this might well be a false positive (hard to tell without the logs) but this would be ignored and wouldn't be the main cause.

The main issue is that the MediaCodec implementation of the H264 encoder on this device fails to output the encoded frame or the metadata. 

We would like to help to see whether it's a device issue or not. Could we ask you to try on another Android device to eliminate the SDK/networking?

P.S. Some background info.. Most of the manufacturers implement H264 hardware accelerated encoder for MediaCodec by wrapping the old OMX/IL implementations. At times, these might be unstable when utilizing as a stream encoder.

**Comment by suryakant-t-yadav** [comment]
Sorry for late reply.
I was running this on multiple deices but got the same error.
device is motorola G4-Plus and Android version is 6.0.1 its alternate name is XT1643.

I get only above error that I have shared.

**Comment by MushMal** [comment]
It's possible that the encoder-related spew is a red herring. Can you confirm - you are trying to run Android demo application right? Is it possible that there is a networking/permission issue? Could you please somehow send the full logs from the beginning?

**Comment by MushMal** [comment]
Ping: Any update on this issue?

**Comment by MushMal** [comment]
Hi there,

I am wondering if you've made any further progress on this issue? Can we be of any help?

**Comment by garishsood** [comment]
Hi @suryakant-t-yadav, 
Let us know if you able to make progress on this issue or if you need further assistance.
