### ISSUE TITLE
S3TransferUtilitySample giving error while uploading

### ISSUE THREAD

**Issue by Hemant0601** [awslabs/aws-sdk-android-samples#196]
I have created a bucket and my pool region , all configuration seems fine as I am using this direct sample only changes I made in the Constant file with adding my details
COGNITO_POOL_ID,
COGNITO_POOL_REGION,
BUCKET_NAME,
BUCKET_REGION
    
but when I try to upload a file I get following error using the mentioned sample. 

 Error during upload: 10
                                                                                      `com.amazonaws.services.s3.model.AmazonS3Exception: Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: F551E8AEBC8F9FC8), S3 Extended Request ID: dkOs2RSapG30uNJzgVHiQmM+I2uhAER2fz/MwVflYzVP5SEnGGoqNhO57Kc4F9md5r5aituXg/8=
                                                                                          at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:729)
                                                                                          at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:405)
                                                                                          at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:212)
                                                                                          at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4643)
                                                                                          at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1747)
                                                                                          at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.uploadSinglePartAndWaitForCompletion(UploadTask.java:214)
                                                                                          at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:88)
                                                                                          at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:47)
                                                                                          at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                          at java.lang.Thread.run(Thread.java:818)`

**Comment by cbommas** [comment]
@Hemant0601 

It looks like that the required permissions are not setup on the S3 bucket. When you create a Cognito Identity pool, it creates 2 roles by default. For the sample to work, you should configure the role named as  Cognito_<IdentityPoolName>Unauth_Role to have read/write access to the bucket. 

Please follow the instructions in the section titled "Setup the required Amazon IAM permissions" on this page - https://docs.aws.amazon.com/aws-mobile/latest/developerguide/how-to-integrate-an-existing-bucket.html

**Comment by Hemant0601** [comment]
@cbommas Ok, I will try that, I have been through the link you are referring to, I by default see two roles for which I was provided permission for which I was able to see two roles, but now in this case I am using same email Id as I have created my OWN AWS account and S3 bucket,
Will try this and update if issues.

**Comment by cbommas** [comment]
@Hemant0601 

Excellent. Please let us know how it goes.

**Comment by Hemant0601** [comment]
@cbommas I guess I was missing something, my pool identity was not created and causing issue, I deleted everything and created all again and is working now.
Thanks
