### ISSUE TITLE
AndroidPubSub re-design question

### ISSUE THREAD

**Issue by matszal** [awslabs/aws-sdk-android-samples#206]
Hi guys, 
i'm new to android and was wondering if you could help me out with re-design of androidpubsub demo app for my project?

I want to use second activity with fragments for each tab and wondering how to pass mqttManager, so I could publish to the topic from other activity?

I've started by passing an intent to other actiity, mqttManager cannot be passed (serializable didnt work either)

Below is a snippet of code from my app:

`View.OnClickListener connect = new View.OnClickListener() {
        @Override
        public void onClick(final View v) {
            Log.d(LOG_TAG, "clientId = " + clientId);

            try {
                mqttManager.connect(clientKeyStore, new AWSIotMqttClientStatusCallback() {
                    @Override
                    public void onStatusChanged(final AWSIotMqttClientStatus status,
                                                final Throwable throwable) {
                    Log.d(LOG_TAG, "Status = " + String.valueOf(status));

                    runOnUiThread(new Runnable() {
                        @Override
                        public void run() {
                            if (status == AWSIotMqttClientStatus.Connecting) {
                                tvStatus.setText("Connecting...");

                            } else if (status == AWSIotMqttClientStatus.Connected) {
                                tvStatus.setText("Connected");
                                btnConnect.setEnabled(false);
                                Intent intent = new Intent(v.getContext(), TabbedActivity.class);
                                intent.putExtra("id",  clientId);
                                intent.putExtra("endPoint",  CUSTOMER_SPECIFIC_ENDPOINT);
                                v.getContext().startActivity(intent);

                            } else if (status == AWSIotMqttClientStatus.Reconnecting) {
                                if (throwable != null) {
                                    Log.e(LOG_TAG, "Connection error.", throwable);
                                }
                                tvStatus.setText("Reconnecting");
                            } else if (status == AWSIotMqttClientStatus.ConnectionLost) {
                                if (throwable != null) {
                                    Log.e(LOG_TAG, "Connection error.", throwable);
                                }
                                tvStatus.setText("Disconnected");
                                btnConnect.setEnabled(true);
                            } else {
                                tvStatus.setText("Disconnected");
                                btnConnect.setEnabled(true);

                            }
                        }
                    });
                    }
                });
            } catch (final Exception e) {
                Log.e(LOG_TAG, "Connection error.", e);
                tvStatus.setText("Error! " + e.getMessage());
            }
        }
    };`

And next part is code in my fragment class:
`public class Tab1Fragment extends Fragment {
    private static final String TAG = "Tab1Fragment";

    AWSIotMqttManager mqttManager;

    //private Button btnTest1;
    private Button btnPublish;
    private Button btnClearAll;
    private TextView incomingText;
    private EditText outgoingtext;

    private String id;
    private String endPoint;

    @Nullable
    @Override
    public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {

        View view = inflater.inflate(R.layout.tab1_fragment, container, false);

        Intent intent = getActivity().getIntent();
        id = intent.getStringExtra("id");
        endPoint = intent.getStringExtra("endPoint");

        subscribe();
        btnPublish = (Button)view.findViewById(R.id.btnPublish);
        btnPublish.setOnClickListener(publishClick);

        btnClearAll = (Button)view.findViewById(R.id.btnClear);

        incomingText = (TextView)view.findViewById(R.id.incomingTxt);

        outgoingtext = (EditText)view.findViewById(R.id.outgoingTxt);

        return view;
    }

    public void subscribe() {

        final String topic = "mytopic/iot";

        Log.d(LOG_TAG, "topic = " + topic);

        try {
            mqttManager.subscribeToTopic(topic, AWSIotMqttQos.QOS0, new AWSIotMqttNewMessageCallback() {
                    @Override
                    public void onMessageArrived(final String topic, final byte[] data) {
                        try {
                            String message = new String(data, "UTF-8");
                            Log.d(LOG_TAG, "Message arrived:");
                            Log.d(LOG_TAG, "   Topic: " + topic);
                            Log.d(LOG_TAG, " Message: " + message);

                            incomingText.setText(message);

                        } catch (UnsupportedEncodingException e) {
                            Log.e(LOG_TAG, "Message encoding error.", e);
                        }
                    }
                });

            } catch (Exception e) {
                Log.e(LOG_TAG, "Subscription error.", e);
            }
        }

    View.OnClickListener publishClick = new View.OnClickListener() {
        @Override
        public void onClick(View v) {

            final String topic = "mytopic/iot";
            final String msg = outgoingtext.getText().toString();

            try {
                mqttManager.publishString(msg, topic, AWSIotMqttQos.QOS0);
            } catch (Exception e) {
                Log.e(LOG_TAG, "Publish error.", e);
            }

        }
    };
}`

And this is the exception:

`java.lang.NullPointerException: Attempt to invoke virtual method 'void com.amazonaws.mobileconnectors.iot.AWSIotMqttManager.subscribeToTopic(java.lang.String, com.amazonaws.mobileconnectors.iot.AWSIotMqttQos, com.amazonaws.mobileconnectors.iot.AWSIotMqttNewMessageCallback)' on a null object reference
                                                                                                                   at com.example.mateusz.homesecurity.Tab1Fragment.subscribe(Tab1Fragment.java:83)
                                                                                                                   at com.example.mateusz.homesecurity.Tab1Fragment.onCreateView(Tab1Fragment.java:59)
                                                                                                                   at android.support.v4.app.Fragment.performCreateView(Fragment.java:2354)
                                                                                                                   at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1419)
                                                                                                                   at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1740)
                                                                                                                   at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1809)
                                                                                                                   at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:799)
                                                                                                                   at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2580)
                                                                                                                   at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2367)
                                                                                                                   at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2322)
                                                                                                                   at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:2199)
                                                                                                                   at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:651)
                                                                                                                   at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:145)
                                                                                                                   at android.support.v4.view.ViewPager.populate(ViewPager.java:1236)
                                                                                                                   at android.support.v4.view.ViewPager.populate(ViewPager.java:1084)
                                                                                                                   at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1614)
                                                                                                                   at android.view.View.measure(View.java:18788)
                                                                                                                   at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                                                                                   at android.support.design.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:714)
                                                                                                                   at android.support.design.widget.HeaderScrollingViewBehavior.onMeasureChild(HeaderScrollingViewBehavior.java:91)
                                                                                                                   at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onMeasureChild(AppBarLayout.java:1361)
                                                                                                                   at android.support.design.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:784)
                                                                                                                   at android.view.View.measure(View.java:18788)
                                                                                                                   at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                                                                                   at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                                                                   at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
                                                                                                                   at android.view.View.measure(View.java:18788)
                                                                                                                   at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                                                                                   at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
                                                                                                                   at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
                                                                                                                   at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
                                                                                                                   at android.view.View.measure(View.java:18788)
                                                                                                                   at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                                                                                   at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                                                                   at android.view.View.measure(View.java:18788)
                                                                                                                   at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                                                                                   at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
                                                                                                                   at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
                                                                                                                   at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
                                                                                                                   at android.view.View.measure(View.java:18788)
                                                                                                                   at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                                                                                   at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                                                                   at com.android.internal.policy.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2643)
                                                                                                                   at android.view.View.measure(View.java:18788)
                                                                                                                   at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2100)
                                                                                                                   at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1216)
                                                                                                                   at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1452)
                                                                                                                   at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
                                                                                                                   at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
                                                                                                               	at android.view.Ch`

**Comment by kvasukib** [comment]
Thank you @matszal for reporting to us. Following are the options:

1. You can have a static reference to the AWSIotMqttManager object in your app so that you can access this static reference in different activities and fragments.

2. You can checkout the aws-android-sdk-iot source code and make AWSIotMqttManager serializable/parcelable which will let you pass the object via intent in Android.

**Comment by matszal** [comment]
@kvasukib Thank you very much for a quick response. I'll test it soon and will report back!

**Comment by kvasukib** [comment]
Thank you for confirming. Closing this issue. Please re-open if you see any further issue.
