### ISSUE TITLE
S3 transfer utitlity sample problem

### ISSUE THREAD

**Issue by matszal** [awslabs/aws-sdk-android-samples#218]
Hi,
I've tried to run S3 android sample app and getting followinf error:

`04-19 19:24:50.058 4460-4460/com.amazonaws.demo.s3transferutility E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.amazonaws.demo.s3transferutility, PID: 4460
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=0, result=-1, data=Intent { dat=content://com.android.externalstorage.documents/document/16F0-2A03:samplea.jpg flg=0x43 }} to activity {com.amazonaws.demo.s3transferutility/com.amazonaws.demo.s3transferutility.UploadActivity}: java.lang.IllegalArgumentException: Invalid file: /storage/emulated/0/samplea.jpg
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4053)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4096)
        at android.app.ActivityThread.-wrap20(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1516)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6077)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
     Caused by: java.lang.IllegalArgumentException: Invalid file: /storage/emulated/0/samplea.jpg
        at com.amazonaws.mobileconnectors.s3.transferutility.TransferUtility.upload(TransferUtility.java:532)
        at com.amazonaws.mobileconnectors.s3.transferutility.TransferUtility.upload(TransferUtility.java:497)
        at com.amazonaws.mobileconnectors.s3.transferutility.TransferUtility.upload(TransferUtility.java:466)
        at com.amazonaws.mobileconnectors.s3.transferutility.TransferUtility.upload(TransferUtility.java:407)
        at com.amazonaws.demo.s3transferutility.UploadActivity.beginUpload(UploadActivity.java:427)
        at com.amazonaws.demo.s3transferutility.UploadActivity.onActivityResult(UploadActivity.java:407)
        at android.app.Activity.dispatchActivityResult(Activity.java:6915)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4049)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4096) 
        at android.app.ActivityThread.-wrap20(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1516) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6077) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756) `

And advise please?

**Comment by minbi** [comment]
Hi @matszal ,

I was not able to reproduce this issue. Are you using an emulator or actual device?

**Comment by matszal** [comment]
@minbi Used emulator, will check now on device
