### ISSUE TITLE
Failed loading native library

### ISSUE THREAD

**Issue by GBoucher42** [awslabs/aws-sdk-android-samples#224]
I was running the application without any problems for 1-2 weeks. Suddenly Today, I cannot run it anymore. I have tried getting the newest version of the sample, and running it again, I get the same issues. Here is the log. It looks as though these librairies should be installed through gradle, So I'm not, sure where I should seek the missing library. Here are my logs.

```
E/KinesisVideoAndroidClient: 2018-05-26T11:23Z T1: EXCEPTION: UnsatisfiedLinkError: Unsatisfied link error. Loading native library KinesisVideoProducerJNI failed with java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.amazonaws.kinesisvideo.demoapp-1/base.apk", zip file "/data/app/com.amazonaws.kinesisvideo.demoapp-1/split_lib_dependencies_apk.apk", zip file "/data/app/com.amazonaws.kinesisvideo.demoapp-1/split_lib_slice_0_apk.apk", zip file "/data/app/com.amazonaws.kinesisvideo.demoapp-1/split_lib_slice_1_apk.apk", zip file "/data/app/com.amazonaws.kinesisvideo.demoapp-1/split_lib_slice_2_apk.apk", zip file "/data/app/com.amazonaws.kinesisvideo.demoapp-1/split_lib_slice_3_apk.apk", zip file "/data/app/com.amazonaws.kinesisvideo.demoapp-1/split_lib_slice_4_apk.apk", zip file "/data/app/com.amazonaws.kinesisvideo.demoapp-1/split_lib_slice_5_apk.apk", zip file "/data/app/com.amazonaws.kinesisvideo.demoapp-1/split_lib_slice_6_apk.apk", zip file "/data/app/com.amazonaws.kinesisvideo.demoapp-1/split_lib_slice_7_apk.apk", zip file "/data/app/com.amazonaws.kinesisvideo.demoapp-1/split_lib_slice_8_apk.apk", zip file "/data/app/com.amazonaws.kinesisvideo.demoapp-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.amazonaws.kinesisvideo.demoapp-1/lib/arm64, /system/lib64, /vendor/lib64]]] couldn't find "libKinesisVideoProducerJNI.so": dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.amazonaws.kinesisvideo.demoapp-1/base.apk", zip file "/data/app/com.amazonaws.kinesisvideo.demoapp-1/split_lib_dependencies_apk.apk", zip file "/data/app/com.amazonaws.kinesisvideo.demoapp-1/split_lib_slice_0_apk.apk", zip file "/data/app/com.amazonaws.kinesisvideo.demoapp-1/split_lib_slice_1_apk.apk", zip file "/data/app/com.amazonaws.kinesisvideo.demoapp-1/split_lib_slice_2_apk.apk", zip file "/data/app/com.amazonaws.kinesisvideo.demoapp-1/split_lib_slice_3_apk.apk", zip file "/data/app/com.amazonaws.kinesisvideo.demoapp-1/split_lib_slice_4_apk.apk", zip file "/data/app/com.amazonaws.kinesisvideo.demoapp-1/split_lib_slice_5_apk.apk", zip file "/data/app/com.amazonaws.kinesisvideo.demoapp-1/split_lib_slice_6_apk.apk", zip file "/data/app/com.amazonaws.kinesisvideo.demoapp-1/split_lib_slice_7_apk.apk", zip file "/data/app/com.amazonaws.kinesisvideo.demoapp-1/split_lib_slice_8_apk.apk", zip file "/data/app/com.amazonaws.kinesisvideo.demoapp-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.amazonaws.kinesisvideo.demoapp-1/lib/arm64, /system/lib64, /vendor/lib64]]] couldn't find "libKinesisVideoProducerJNI.so"
E/StreamConfigurationFragment: Failed to create Kinesis Video client
                               com.amazonaws.kinesisvideo.producer.ProducerException: Failed loading native library
                                   at com.amazonaws.kinesisvideo.producer.jni.NativeKinesisVideoProducerJni.initializeLibrary(NativeKinesisVideoProducerJni.java:1091)
                                   at com.amazonaws.kinesisvideo.producer.jni.NativeKinesisVideoProducerJni.create(NativeKinesisVideoProducerJni.java:237)
                                   at com.amazonaws.kinesisvideo.producer.jni.NativeKinesisVideoProducerJni.createSync(NativeKinesisVideoProducerJni.java:255)
                                   at com.amazonaws.kinesisvideo.producer.jni.NativeKinesisVideoProducerJni.createSync(NativeKinesisVideoProducerJni.java:221)
                                   at com.amazonaws.kinesisvideo.client.NativeKinesisVideoClient.initialize(NativeKinesisVideoClient.java:129)
                                   at com.amazonaws.mobileconnectors.kinesisvideo.client.KinesisVideoAndroidClientFactory.createKinesisVideoClient(KinesisVideoAndroidClientFactory.java:139)
                                   at com.amazonaws.mobileconnectors.kinesisvideo.client.KinesisVideoAndroidClientFactory.createKinesisVideoClient(KinesisVideoAndroidClientFactory.java:114)
                                   at com.amazonaws.kinesisvideo.demoapp.fragment.StreamConfigurationFragment.onCreateView(StreamConfigurationFragment.java:70)
                                   at android.support.v4.app.Fragment.performCreateView(Fragment.java:2080)
                                   at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1108)
                                   at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1290)
                                   at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:801)
                                   at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1677)
                                   at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:388)
                                   at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:604)
                                   at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
                                   at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1249)
                                   at android.app.Activity.performStart(Activity.java:6771)
                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2689)
                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2787)
                                   at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1504)
                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                   at android.os.Looper.loop(Looper.java:154)
                                   at android.app.ActivityThread.main(ActivityThread.java:6247)
                                   at java.lang.reflect.Method.invoke(Native Method)
                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:872)
                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.amazonaws.kinesisvideo.demoapp, PID: 14671
                  java.lang.RuntimeException: Unable to start activity ComponentInfo{com.amazonaws.kinesisvideo.demoapp/com.amazonaws.kinesisvideo.demoapp.activity.SimpleNavActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.List com.amazonaws.kinesisvideo.client.KinesisVideoClient.listSupportedConfigurations()' on a null object reference
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2726)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2787)
                      at android.app.ActivityThread.-wrap12(ActivityThread.java)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1504)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6247)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:872)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
                   Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.List com.amazonaws.kinesisvideo.client.KinesisVideoClient.listSupportedConfigurations()' on a null object reference
                      at com.amazonaws.mobileconnectors.kinesisvideo.util.CameraUtils.getCameras(CameraUtils.java:62)
                      at com.amazonaws.kinesisvideo.demoapp.fragment.StreamConfigurationFragment.onCreateView(StreamConfigurationFragment.java:83)
                      at android.support.v4.app.Fragment.performCreateView(Fragment.java:2080)
                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1108)
                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1290)
                      at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:801)
                      at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1677)
                      at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:388)
                      at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:604)
                      at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
                      at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1249)
                      at android.app.Activity.performStart(Activity.java:6771)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2689)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2787) 
                      at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1504) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:154) 
                      at android.app.ActivityThread.main(ActivityThread.java:6247) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:872) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762) 
Application terminated.
```

**Comment by GBoucher42** [comment]
It works if I manually replace the reference in the gradle build for 2.6.14. Is it possible that the last version of the sdk is broken?

**Comment by minbi** [comment]
Thanks for reporting the issue. We will look into this.

**Comment by raghavk92** [comment]
been having the same issue.Is there any workaround for now?

**Comment by GBoucher42** [comment]
@raghavk92  I changed the dependencies in the build.gradle dow the aws sdk.

compile ('com.amazonaws:aws-android-sdk-kinesisvideo:2.6.14') { transitive = true; }

**Comment by raghavk92** [comment]
@GBoucher42 i tried. it worked but now the streaming is showing loading for like 10 seconds then shows video for 4-5 seconds. And super.onResume() workaround in another issue that you specified does not help.

**Comment by muellerfr** [comment]
Closing this issue as the problem was resolved. If you have a separate problem, please open another issue in aws/aws-sdk-android.
