### ISSUE TITLE
    java.lang.UnsatisfiedLinkError: dlopen failed: library "libcamera2ndk.so" not found

### ISSUE THREAD

**Issue by NehaKushwah993** [awslabs/aws-sdk-android-samples#232]
Getting crash for API <24 devices : 

com.amazon.sumerianarcorestarter E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.amazon.sumerianarcorestarter, PID: 11355
    java.lang.UnsatisfiedLinkError: dlopen failed: library "libcamera2ndk.so" not found
        at java.lang.Runtime.loadLibrary(Runtime.java:372)
        at java.lang.System.loadLibrary(System.java:1076)
        at com.google.ar.core.Session.<init>(Session.java:97)
        at com.amazon.sumerianarcorestarter.MainActivity.onResume(MainActivity.java:93)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1326)
        at android.app.Activity.performResume(Activity.java:6323)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3311)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3359)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1438)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:168)
        at android.app.ActivityThread.main(ActivityThread.java:5845)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)

**Comment by NehaKushwah993** [comment]
Wrong window, sorry!
