### ISSUE TITLE
Android:TransferUtility SDK : SocketTimeout Exception

### ISSUE THREAD

**Issue by bhoopendrayash** [awslabs/aws-sdk-android-samples#233]
SDK : TransferUtility
Version : 2.6.23
Frequency : very high on low network  while its work fine on good network 
Device :all most on all device  
Socket and connection time out setting : 10 min. 
stack trace: 

```
com.amazonaws.AmazonClientException: ****Unable to execute HTTP request: timeout
   at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:441)****
   at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:212)
   at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4659)
   at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1752)
   at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.uploadSinglePartAndWaitForCompletion(UploadTask.java:219)
   at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:93)
   at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:49)
   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
   at java.lang.Thread.run(Thread.java:764)
**Caused by: java.net.SocketTimeoutException: timeout
   at com.android.okhttp.okio.Okio$3.newTimeoutException(Okio.java:221)**
   at com.android.okhttp.okio.AsyncTimeout.exit(AsyncTimeout.java:250)
   at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:217)
   at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:316)
   at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:310)
   at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:206)
   at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:385)
   at com.android.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:144)
   at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:917)
   at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:789)
   at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:499)
   at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:435)
   at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseMessage(HttpURLConnectionImpl.java:562)
   at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseMessage(DelegatingHttpsURLConnection.java:109)
   at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseMessage(Unknown Source:0)
   at com.amazonaws.http.UrlHttpClient.createHttpResponse(UrlHttpClient.java:92)
   at com.amazonaws.http.UrlHttpClient.execute(UrlHttpClient.java:85)
   at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:371)
   at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:212) 
   at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4659) 
   at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1752) 
   at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.uploadSinglePartAndWaitForCompletion(UploadTask.java:219) 
   at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:93) 
   at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:49) 
   at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
   at java.lang.Thread.run(Thread.java:764)  
```

**Comment by minbi** [comment]
Hi @bhoopendrayash ,

In this situation, are you expecting a retry and not seeing that it is happenning?

**Comment by bhoopendrayash** [comment]
1.  we have already implemented retry functionality in our code as provided by aws sdk, 

2.  But ,after 3 retries we did not receive any callback  .

Please let me know if you need more information .

**Comment by kvasukib** [comment]
@bhoopendrayash Sorry for the delayed response. Can you resume the transfer when you get this exception?
