### ISSUE TITLE
Android:TransferUtility S3Upload Issue 

### ISSUE THREAD

**Issue by bhoopendrayash** [awslabs/aws-sdk-android-samples#239]
SDK : TransferUtility
Version : 2.6.23
Frequency : very high on low network 
Device :all devices
Socket and connection time out setting : 10 min.
stack trace:

```
UploadPartTask: Encountered error uploading part 
                                                           com.amazonaws.AmazonClientException: Unable to execute HTTP request: timeout
                                                               at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:441)
                                                               at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:212)
                                                               at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4659)
                                                               at com.amazonaws.services.s3.AmazonS3Client.uploadPart(AmazonS3Client.java:3676)
                                                               at com.amazonaws.mobileconnectors.s3.transferutility.UploadPartTask.call(UploadPartTask.java:64)
                                                               at com.amazonaws.mobileconnectors.s3.transferutility.UploadPartTask.call(UploadPartTask.java:30)
                                                               at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                                                               at java.lang.Thread.run(Thread.java:764)
                                                            Caused by: java.net.SocketTimeoutException: timeout
                                                               at com.android.okhttp.okio.Okio$3.newTimeoutException(Okio.java:221)
                                                               at com.android.okhttp.okio.AsyncTimeout.exit(AsyncTimeout.java:250)
                                                               at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:217)
                                                               at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:316)
                                                               at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:310)
                                                               at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:206)
                                                               at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:385)
                                                               at com.android.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:144)
                                                               at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:917)
                                                               at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:789)
                                                               at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:499)
                                                               at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:435)
                                                               at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseMessage(HttpURLConnectionImpl.java:562)
                                                               at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseMessage(DelegatingHttpsURLConnection.java:109)
                                                               at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseMessage(Unknown Source:0)
                                                               at com.amazonaws.http.UrlHttpClient.createHttpResponse(UrlHttpClient.java:92)
                                                               at com.amazonaws.http.UrlHttpClient.execute(UrlHttpClient.java:85)
                                                               at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:371)
                                                               at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:212) 
                                                               at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4659) 
                                                               at com.amazonaws.services.s3.AmazonS3Client.uploadPart(AmazonS3Client.java:3676) 
                                                               at com.amazonaws.mobileconnectors.s3.transferutility.UploadPartTask.call(UploadPartTask.java:64) 
                                                               at com.amazonaws.mobileconnectors.s3.transferutility.UploadPartTask.call(UploadPartTask.java:30) 
                                                               at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
                                                               at java.lang.Thread.run(Thread.java:764) 
```

**Comment by desokroshan** [comment]
@bhoopendrayash Thanks for reaching out. Apologies for the inconvenience caused.

Can you please post a snippet that can reproduce the issue? It will greatly assist in investigating the issue.

Thanks.

**Comment by bhoopendrayash** [comment]
just try to upload high resolution video on s3 server from any device in slow network

**Comment by bhoopendrayash** [comment]
Thanks @kvasukib  for reply . my app video size less then 20 Mb , its working fine in good network condition but in slow network its throw time out error . i am using below code for upload image and vidoe 

   /**
     * Gets an instance of CognitoCachingCredentialsProvider which is
     * constructed using the given Context.
     *
     * @param context An Context instance.
     * @return A default credential provider.
     */
    private static CognitoCachingCredentialsProvider getCredProvider(Context context) {
        if (sCredProvider == null) {
            // Bhoopendra : Added  timeout configuration
            ClientConfiguration clientConfiguration = new ClientConfiguration();
            clientConfiguration.setConnectionTimeout(300000);
            clientConfiguration.setSocketTimeout(300000);
            clientConfiguration.setMaxErrorRetry(10);
           // clientConfiguration.setRetryPolicy(new RetryPolicy(null,null,10,true));
            clientConfiguration.setMaxConnections(10);
            clientConfiguration.setProtocol(Protocol.HTTPS);
           // clientConfiguration.setEnableGzip(true);
            Log.d("CONNETIMEOUT.S3", "" + clientConfiguration.getConnectionTimeout());
            Log.d("getSocketTimeout.S3", "" + clientConfiguration.getSocketTimeout());


            sCredProvider = new CognitoCachingCredentialsProvider(
                    context,
                    AppConstant.COGNITO_POOL_ID,
                    Regions.fromName(AppConstant.COGNITO_POOL_REGION), clientConfiguration);

        }
        return sCredProvider;
    }

    /**
     * Gets an instance of a S3 client which is constructed using the given
     * Context.
     *
     * @param context An Context instance.
     * @return A default S3 client.
     */

    public static AmazonS3Client getS3Client(Context context) {
       // final CountDownLatch countDownLatch = new CountDownLatch(1);
        // if (sS3Client == null) {
        sS3Client = new AmazonS3Client(getCredProvider(context));
        sS3Client.setRegion(Region.getRegion(Regions.fromName(AppConstant.BUCKET_REGION)));
        S3ClientOptions s3ClientOptions = S3ClientOptions.builder().setAccelerateModeEnabled(true).build();
        sS3Client.setS3ClientOptions(s3ClientOptions);
        Log.d("isAccelerateModeEnabled", "" + s3ClientOptions.isAccelerateModeEnabled());

        return sS3Client;
    }


    /**
     * Gets an instance of the TransferUtility which is constructed using the
     * given Context
     *
     * @param context
     * @return a TransferUtility instance
     */
    /**
     * TransferServiceCheckTimeInterval The TransferUtility monitors each on-going transfer by checking its status periodically.
     * If a stalled transfer is detected, it will be automatically resumed by the TransferUtility. T
     * he TransferServiceCheckTimeInterval option allows you to set the time interval between the status checks.
     * It is specified in milliseconds and set to 60,000 by default.
     *
     * @param context
     * @return
     */
    public static TransferUtility getTransferUtility(Context context) {
        if (sTransferUtility == null) {
            TransferUtilityOptions options = new TransferUtilityOptions();
            options.setTransferThreadPoolSize(2);
            long checkSomeInterVal = 1 * 60 * 1000;// 1-minutes
            options.setTransferServiceCheckTimeInterval(checkSomeInterVal);
            sTransferUtility = TransferUtility.builder().transferUtilityOptions(options)
                    .context(context.getApplicationContext()).defaultBucket(AppConstant.BUCKET_NAME)
                    .s3Client(getS3Client(context.getApplicationContext()))
                    .build();
        }
        return sTransferUtility;
    }

Note : I have enable AccelerateModeEnabled on S3 server as well

**Comment by kvasukib** [comment]
@bhoopendrayash Thank you for the detailed response. Have you tried attaching a retry policy to the Client Configuration?

**Comment by bhoopendrayash** [comment]
yes , I tried but no luck

**Comment by kvasukib** [comment]
@bhoopendrayash Sorry for the delayed response. Can you find the number of available processors in the device? You can get this from `Runtime.getRuntime().getAvailableProcessors()?`

**Comment by bhoopendrayash** [comment]
I have also tried with S3TransferUtilitySample App , this sample app also has same issue .

**Comment by jagdev7dayz** [comment]
Amazon guys, its long pending issue, please give your proper view on this so we can take correct decision to continue amazon SDK or any other alternate for our upload mechanism.
We are stuck for this to release our app on market.

This issue is only in android SDK for iOS its working fine.

Thanks

**Comment by bhoopendrayash** [comment]
As per my understanding this issue is related to " Okio" time out .in slow network if app is not able to wright in any data on s3 bucket within 20 second then okio internally throw a time out error . its looks like a OKIO time out rather then socket time out of s3 bucket

**Comment by kvasukib** [comment]
Closing this issue @bhoopendrayash. Please feel free to reopen if you face the issue with TransferUtility.
