### ISSUE TITLE
Continuously getting java.net.SocketException after video upload failed on slow network.

### ISSUE THREAD

**Issue by Dheeraj-yash** [awslabs/aws-sdk-android-samples#250]
i am getting java.net.SocketException: socket is closed error when i try to upload vidoe on s3 server once i received socket time out then it will throw time out for every request 

please let me know this issue is related to client (S3 transfer utility sdk ) or server S3 console configuration 

below is the stack trace of the exception :

```
com.amazonaws.AmazonClientException: Unable to execute HTTP request: timeout
at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:441)
at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:212)
at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4659)
at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1752)
at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.uploadSinglePartAndWaitForCompletion(UploadTask.java:219)
at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:93)
at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:49)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
at java.lang.Thread.run(Thread.java:764)
Caused by: java.net.SocketTimeoutException: timeout
at com.android.okhttp.okio.Okio$3.newTimeoutException(Okio.java:212)
at com.android.okhttp.okio.AsyncTimeout.exit(AsyncTimeout.java:261)
at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:215)
at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:306)
at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:300)
at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)
at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:186)
at com.android.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:127)
at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:737)
at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:609)
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:471)
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:407)
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseMessage(HttpURLConnectionImpl.java:534)
at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseMessage(DelegatingHttpsURLConnection.java:109)
at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseMessage(Unknown Source:0)
at com.amazonaws.http.UrlHttpClient.createHttpResponse(UrlHttpClient.java:92)
at com.amazonaws.http.UrlHttpClient.execute(UrlHttpClient.java:85)
at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:371)
at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:212) 
at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4659) 
at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1752) 
at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.uploadSinglePartAndWaitForCompletion(UploadTask.java:219) 
at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:93) 
at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:49) 
at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
at java.lang.Thread.run(Thread.java:764) 
Caused by: java.net.SocketException: socket is closed
at com.android.org.conscrypt.ConscryptFileDescriptorSocket$SSLInputStream.read(ConscryptFileDescriptorSocket.java:546)
at com.android.okhttp.okio.Okio$2.read(Okio.java:136)
at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:306) 
at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:300) 
at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196) 
at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:186) 
at com.android.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:127) 
at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:737) 
at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:609) 
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:471) 
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:407) 
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseMessage(HttpURLConnectionImpl.java:534) 
at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseMessage(DelegatingHttpsURLConnection.java:109) 
at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseMessage(Unknown Source:0) 
at com.amazonaws.http.UrlHttpClient.createHttpResponse(UrlHttpClient.java:92) 
at com.amazonaws.http.UrlHttpClient.execute(UrlHttpClient.java:85) 
at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:371) 
at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:212) 
at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4659) 
at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1752) 
at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.uploadSinglePartAndWaitForCompletion(UploadTask.java:219) 
at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:93) 
at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:49) 
at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
at java.lang.Thread.run(Thread.java:764)
```

**Comment by kvasukib** [comment]
Thank you for reporting to us. Sorry for the inconvenience caused.

What version of SDK are you using? 
What is the size of the file you are uploading? 
Is the app in the background when the upload is happening? 
Do you have a custom ClientConfiguration that you are attaching to the AmazonS3Client?

**Comment by Dheeraj-yash** [comment]
Thanks for you quick response @kvasukib  
here is details :
sdk : 2.6.30
file size : 50mb
not in background
not custom.

**Comment by kvasukib** [comment]
@Dheeraj-yash S3 has an idle connection timeout of 20 seconds. If the device is not sending data due to memory pressure or slow network, S3 will close the connection after waiting for 20 seconds. Does this happen for every upload or for certain uploads?

**Comment by Dheeraj-yash** [comment]
Thanks @kvasukib :  It happen only for slow network but not for all time. Is there any way to increase/configure idle connection timeout for S3 ?

**Comment by kvasukib** [comment]
@Dheeraj-yash Sorry for the inconvenience caused. S3 has a 20 second idle timeout and it cannot be altered. However I have few solutions for you:

1) You can resume the transfer when the transfer fails. When the transfer fails, we notify with TransferState.FAILED in onStateChanged callback of the TransferListener. You can check for this state and resume the transfer.

```java
TransferObserver transferObserver = transferUtility.upload(key, file);
transferObserver.setTransferListener(new TransferListener() {
            @Override
            public void onStateChanged(int id, TransferState state) {
                Log.i(LOG_TAG, "onStateChanged = " + state);

                if (TransferState.FAILED == state) {
                    transferUtility.resume(transferObserver.getId());
                }
            }

            @Override
            public void onProgressChanged(int id, long bytesCurrent, long bytesTotal) {
                float percentDonef = ((float) bytesCurrent / (float) bytesTotal) * 100;
                int percentDone = (int)percentDonef;

                Log.i(LOG_TAG, "ID:" + id + " bytesCurrent: " + bytesCurrent
                        + " bytesTotal: " + bytesTotal + " " + percentDone + "%");
            }

            @Override
            public void onError(int id, Exception ex) {
                // Handle errors
                ex.printStackTrace();
                Log.e(LOG_TAG, "Error uploading", ex);
            }
        });
```

2) You can configure the number of threads in the pool that can work to upload/download the data. If the number of available processors on the device is N, we create a pool of N + 1 threads for multi-part uploads and N + 1 threads for single-part uploads and downloads. You can change N by using the `TransferUtilityOptions` (https://docs.aws.amazon.com/aws-mobile/latest/developerguide/how-to-transfer-files-with-transfer-utility.html). 

For example, if you restrict the uploads to do just single-part, the transfers would be slow but the connection will not be idle.

Have you noticed the same error on a moderate / better network?

**Comment by muellerfr** [comment]
This issue has been automatically closed because of inactivity. Please open a new issue in https://github.com/aws/aws-sdk-android/issues if you are still encountering problems.
