### ISSUE TITLE
Error Could not validate Certificate

### ISSUE THREAD

**Issue by akinnuwa** [awslabs/aws-sdk-android-samples#26]
12 23:23:13.882  20555-20751/com.overdrivedx.boxmentd I/AmazonHttpClient﹕ Unable to execute HTTP request: com.android.org.bouncycastle.jce.exception.ExtCertPathValidatorException: Could not validate certificate: current time: Fri Apr 12 23:23:13 CET 2013, validation time: Thu Oct 31 01:00:00 CET 2013
    javax.net.ssl.SSLHandshakeException: com.android.org.bouncycastle.jce.exception.ExtCertPathValidatorException: Could not validate certificate: current time: Fri Apr 12 23:23:13 CET 2013, validation time: Thu Oct 31 01:00:00 CET 2013
            at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:381)
            at libcore.net.http.HttpConnection.setupSecureSocket(HttpConnection.java:209)
            at libcore.net.http.HttpsURLConnectionImpl$HttpsEngine.makeSslConnection(HttpsURLConnectionImpl.java:478)
            at libcore.net.http.HttpsURLConnectionImpl$HttpsEngine.connect(HttpsURLConnectionImpl.java:433)
            at libcore.net.http.HttpEngine.sendSocketRequest(HttpEngine.java:290)
            at libcore.net.http.HttpEngine.sendRequest(HttpEngine.java:240)
            at libcore.net.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:81)
            at libcore.net.http.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:205)
            at libcore.net.http.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:281)
            at com.amazonaws.http.UrlHttpClient.writeContentToConnection(UrlHttpClient.java:128)
            at com.amazonaws.http.UrlHttpClient.execute(UrlHttpClient.java:65)
            at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:353)
            at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:196)
            at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.invoke(AmazonCognitoIdentityClient.java:455)
            at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.getId(AmazonCognitoIdentityClient.java:290)
            at com.amazonaws.auth.AWSAbstractCognitoIdentityProvider.getIdentityId(AWSAbstractCognitoIdentityProvider.java:170)
            at com.amazonaws.auth.AWSEnhancedCognitoIdentityProvider.refresh(AWSEnhancedCognitoIdentityProvider.java:76)
            at com.amazonaws.auth.CognitoCredentialsProvider.startSession(CognitoCredentialsProvider.java:537)
            at com.amazonaws.auth.CognitoCredentialsProvider.getCredentials(CognitoCredentialsProvider.java:370)
            at com.amazonaws.auth.CognitoCachingCredentialsProvider.getCredentials(CognitoCachingCredentialsProvider.java:440)
            at com.amazonaws.auth.CognitoCachingCredentialsProvider.getCredentials(CognitoCachingCredentialsProvider.java:76)
            at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4228)
            at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1644)
            at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.uploadSinglePartAndWaitForCompletion(UploadTask.java:183)
            at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:73)
            at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:39)
            at java.util.concurrent.FutureTask.run(FutureTask.java:234)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
            at java.lang.Thread.run(Thread.java:838)
     Caused by: java.security.cert.CertificateException: com.android.org.bouncycastle.jce.exception.ExtCertPathValidatorException: Could not validate certificate: current time: Fri Apr 12 23:23:13 CET 2013, validation time: Thu Oct 31 01:00:00 CET 2013
            at org.apache.harmony.xnet.provider.jsse.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:296)
            at org.apache.harmony.xnet.provider.jsse.TrustManagerImpl.checkServerTrusted(TrustManagerImpl.java:197)
            at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:584)
            at org.apache.harmony.xnet.provider.jsse.NativeCrypto.SSL_do_handshake(Native Method)
            at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:378)
            at libcore.net.http.HttpConnection.setupSecureSocket(HttpConnection.java:209)
            at libcore.net.http.HttpsURLConnectionImpl$HttpsEngine.makeSslConnection(HttpsURLConnectionImpl.java:478)
            at libcore.net.http.HttpsURLConnectionImpl$HttpsEngine.connect(HttpsURLConnectionImpl.java:433)
            at libcore.net.http.HttpEngine.sendSocketRequest(HttpEngine.java:290)
            at libcore.net.http.HttpEngine.sendRequest(HttpEngine.java:240)
            at libcore.net.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:81)
            at libcore.net.http.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:205)
            at libcore.net.http.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:281)
            at com.amazonaws.http.UrlHttpClient.writeContentToConnection(UrlHttpClient.java:128)
            at com.amazonaws.http.UrlHttpClient.execute(UrlHttpClient.java:65)
            at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:353)
            at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:196)
            at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.invoke(AmazonCognitoIdentityClient.java:455)
            at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.getId(AmazonCognitoIdentityClient.java:290)
            at com.amazonaws.auth.AWSAbstractCognitoIdentityProvider.getIdentityId(AWSAbstractCognitoIdentityProvider.java:170)
            at com.amazonaws.auth.AWSEnhancedCognitoIdentityProvider.refresh(AWSEnhancedCognitoIdentityProvider.java:76)
            at com.amazonaws.auth.CognitoCredentialsProvider.startSession(CognitoCredentialsProvider.java:537)
            at com.amazonaws.auth.CognitoCredentialsProvider.getCredentials(CognitoCredentialsProvider.java:370)
            at com.amazonaws.auth.CognitoCachingCredentialsProvider.getCredentials(CognitoCachingCredentialsProvider.java:440)
            at com.amazonaws.auth.CognitoCachingCredentialsProvider.getCredentials(CognitoCachingCredentialsProvider.java:76)
            at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4228)
            at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1644)
            at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.uploadSinglePartAndWaitForCompletion(UploadTask.java:183)
            at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:73)
            at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:39)
            at java.util.concurrent.FutureTask.run(FutureTask.java:234)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
            at java.lang.Thread.run(Thread.java:838)
     Caused by: com.android.org.bouncycastle.jce.exception.ExtCertPathValidatorException: Could not validate cert
04-12 23:23:13.883  20555-20751/com.overdrivedx.boxmentd E/UploadTask﹕ Unable to execute HTTP request: com.android.org.bouncycastle.jce.exception.ExtCertPathValidatorException: Could not validate certificate: current time: Fri Apr 12 23:23:13 CET 2013, validation time: Thu Oct 31 01:00:00 CET 2013
04-12 23:23:13.899  20555-20555/com.overdrivedx.boxmentd E/TAG﹕ Transfer failed.
04-12 23:23:23.898  20555-20751/com.overdrivedx.boxmentd D/dalvikvm﹕ threadid=14: exiting
04-12 23:23:23.899  20555-20751/com.overdrivedx.boxmentd D/dalvikvm﹕ threadid=14: bye!
04-12 23:24:10.046  20555-20750/com.overdrivedx.boxmentd D/dalvikvm﹕ threadid=13: exiting
04-12 23:24:10.048  20555-20750/com.overdrivedx.boxmentd D/dalvikvm﹕ threadid=13: bye!

**Comment by akinnuwa** [comment]
found out my date on the device was 2 years ago! resetting the date to the correct date solved it

**Comment by irvins** [comment]
oh man i just ran into this exact issue.   my date was 3 years ago!  im so happy i found this thread, i was just searching for "com.android.org.bouncycastle.jce.exception.ExtCertPathValidatorException: Could not validate certificate"

thank you!
