### ISSUE TITLE
Stream is not displaying correctly on Kinesis Console

### ISSUE THREAD

**Issue by marujeyakumar** [awslabs/aws-sdk-android-samples#269]
Hi,
I am running the Kinesis Video demo app on a One Plus 6T device. I'm only able to get a few seconds (if not any seconds) of video content displaying on the Kinesis console. When I check the application logs, I see the following exception repeatedly. Anything I can do to fix this? Is this a problem with the application or the Kinesis Console I am sending the video data to? Thanks in advance! 

E/AndroidCameraMediaSource: error updating sink with frame
    com.amazonaws.kinesisvideo.producer.ProducerException: Failed to put a frame into the stream. StatusCode: 0x3200000d
        at com.amazonaws.kinesisvideo.internal.producer.jni.NativeKinesisVideoProducerJni.putKinesisVideoFrame(Native Method)
        at com.amazonaws.kinesisvideo.internal.producer.jni.NativeKinesisVideoProducerJni.putFrame(NativeKinesisVideoProducerJni.java:495)
        at com.amazonaws.kinesisvideo.internal.producer.jni.NativeKinesisVideoProducerStream.putFrame(NativeKinesisVideoProducerStream.java:292)
        at com.amazonaws.kinesisvideo.internal.mediasource.ProducerStreamSink.onFrame(ProducerStreamSink.java:52)
        at com.amazonaws.mobileconnectors.kinesisvideo.mediasource.android.AndroidCameraMediaSource$2.onFrameAvailable(AndroidCameraMediaSource.java:266)
        at com.amazonaws.mobileconnectors.kinesisvideo.encoding.EncoderWrapper.sendEncodedFrameToProducerSDK(EncoderWrapper.java:198)
        at com.amazonaws.mobileconnectors.kinesisvideo.encoding.EncoderWrapper.processEncodedData(EncoderWrapper.java:164)
        at com.amazonaws.mobileconnectors.kinesisvideo.encoding.EncoderWrapper.processEncoderOutputBuffer(EncoderWrapper.java:145)
        at com.amazonaws.mobileconnectors.kinesisvideo.encoding.EncoderWrapper.getDataFromEncoder(EncoderWrapper.java:121)
        at com.amazonaws.mobileconnectors.kinesisvideo.encoding.EncoderWrapper.encodeFrame(EncoderWrapper.java:94)
        at com.amazonaws.mobileconnectors.kinesisvideo.camera.CameraFramesSource$1.onImageAvailable(CameraFramesSource.java:68)
        at android.media.ImageReader$ListenerHandler.handleMessage(ImageReader.java:800)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6863)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by muellerfr** [comment]
Hi @marujeyakumar,

we're not tracking all issues in the SDK repos. I ported the issue over there, and will close this issue.
https://github.com/aws-amplify/aws-sdk-android/issues/581
