### ISSUE TITLE
Error Using ProGuard with the AWS SDK for Android

### ISSUE THREAD

**Issue by achinverma** [awslabs/aws-sdk-android-samples#39]
I am using aws sdk jar files in android to upload the file but i am not able to generate the signed apk with proguard , i am getting below warnings. i have used aws-android-sdk-core-2.2.9.jar and aws-android-sdk-s3-2.2.9.jar and i am getting below , please anyone guide me? Proguard returned with error code 1. See console

[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.AmazonWebServiceClient: can't find referenced class org.apache.commons.logging.LogFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.AmazonWebServiceClient: can't find referenced class org.apache.commons.logging.LogFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.auth.AWS3Signer: can't find referenced class org.apache.commons.logging.LogFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.auth.AWS3Signer: can't find referenced class org.apache.commons.logging.LogFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.auth.AWS4Signer: can't find referenced class org.apache.commons.logging.LogFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.auth.AWS4Signer: can't find referenced class org.apache.commons.logging.LogFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.auth.AWSCredentialsProviderChain: can't find referenced class org.apache.commons.logging.LogFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.auth.AWSCredentialsProviderChain: can't find referenced class org.apache.commons.logging.LogFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.auth.AwsChunkedEncodingInputStream: can't find referenced class org.apache.commons.logging.LogFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.auth.AwsChunkedEncodingInputStream: can't find referenced class org.apache.commons.logging.LogFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.auth.DecodedStreamBuffer: can't find referenced class org.apache.commons.logging.LogFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.auth.DecodedStreamBuffer: can't find referenced class org.apache.commons.logging.LogFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.auth.policy.internal.JsonPolicyWriter: can't find referenced class org.apache.commons.logging.LogFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.auth.policy.internal.JsonPolicyWriter: can't find referenced class org.apache.commons.logging.LogFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.event.ProgressListenerChain: can't find referenced class org.apache.commons.logging.LogFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.event.ProgressListenerChain: can't find referenced class org.apache.commons.logging.LogFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.http.AmazonHttpClient: can't find referenced class org.apache.commons.logging.LogFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.http.AmazonHttpClient: can't find referenced class org.apache.commons.logging.LogFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.http.AmazonHttpClient: can't find referenced class org.apache.commons.logging.LogFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.http.DefaultErrorResponseHandler: can't find referenced class org.apache.commons.logging.LogFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.http.DefaultErrorResponseHandler: can't find referenced class org.apache.commons.logging.LogFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.http.HttpMethodReleaseInputStream: can't find referenced class org.apache.commons.logging.LogFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.http.HttpMethodReleaseInputStream: can't find referenced class org.apache.commons.logging.LogFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.http.IdleConnectionReaper: can't find referenced class org.apache.commons.logging.LogFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.http.IdleConnectionReaper: can't find referenced class org.apache.commons.logging.LogFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.http.JsonResponseHandler: can't find referenced class org.apache.commons.logging.LogFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.http.JsonResponseHandler: can't find referenced class org.apache.commons.logging.LogFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.http.RepeatableInputStreamRequestEntity: can't find referenced class org.apache.commons.logging.LogFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.http.RepeatableInputStreamRequestEntity: can't find referenced class org.apache.commons.logging.LogFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.http.StaxResponseHandler: can't find referenced class org.apache.commons.logging.LogFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.http.StaxResponseHandler: can't find referenced class org.apache.commons.logging.LogFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.http.conn.ClientConnectionManagerFactory: can't find referenced class org.apache.commons.logging.LogFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.http.conn.ClientConnectionManagerFactory: can't find referenced class org.apache.commons.logging.LogFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.http.conn.ClientConnectionRequestFactory: can't find referenced class org.apache.commons.logging.LogFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.http.conn.ClientConnectionRequestFactory: can't find referenced class org.apache.commons.logging.LogFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.internal.SdkInputStream: can't find referenced class org.apache.commons.logging.LogFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.internal.SdkInputStream: can't find referenced class org.apache.commons.logging.LogFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.internal.config.InternalConfig: can't find referenced class org.apache.commons.logging.LogFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.internal.config.InternalConfig: can't find referenced class org.apache.commons.logging.LogFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.metrics.AwsSdkMetrics: can't find referenced class org.apache.commons.logging.LogFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.metrics.AwsSdkMetrics: can't find referenced class org.apache.commons.logging.LogFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.metrics.ServiceLatencyProvider: can't find referenced class org.apache.commons.logging.LogFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.metrics.ServiceLatencyProvider: can't find referenced class org.apache.commons.logging.LogFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.mobileconnectors.s3.transfermanager.TransferManager: can't find referenced class org.apache.commons.logging.LogFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.mobileconnectors.s3.transfermanager.TransferManager: can't find referenced class org.apache.commons.logging.LogFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.mobileconnectors.s3.transfermanager.TransferProgress: can't find referenced class org.apache.commons.logging.LogFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.mobileconnectors.s3.transfermanager.TransferProgress: can't find referenced class org.apache.commons.logging.LogFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.mobileconnectors.s3.transfermanager.internal.CopyCallable: can't find referenced class org.apache.commons.logging.LogFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.mobileconnectors.s3.transfermanager.internal.CopyCallable: can't find referenced class org.apache.commons.logging.LogFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.mobileconnectors.s3.transfermanager.internal.UploadCallable: can't find referenced class org.apache.commons.logging.LogFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.mobileconnectors.s3.transfermanager.internal.UploadCallable: can't find referenced class org.apache.commons.logging.LogFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.mobileconnectors.s3.transfermanager.internal.UploadMonitor: can't find referenced class org.apache.commons.logging.LogFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.mobileconnectors.s3.transfermanager.internal.UploadMonitor: can't find referenced class org.apache.commons.logging.LogFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.regions.RegionUtils: can't find referenced class org.apache.commons.logging.LogFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.regions.RegionUtils: can't find referenced class org.apache.commons.logging.LogFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.services.s3.AmazonS3Client: can't find referenced class org.apache.commons.logging.LogFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.services.s3.AmazonS3Client: can't find referenced class org.apache.commons.logging.LogFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.services.s3.internal.AbstractS3ResponseHandler: can't find referenced class org.apache.commons.logging.LogFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.services.s3.internal.AbstractS3ResponseHandler: can't find referenced class org.apache.commons.logging.LogFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.services.s3.internal.Constants: can't find referenced class org.apache.commons.logging.LogFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.services.s3.internal.Constants: can't find referenced class org.apache.commons.logging.LogFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.services.s3.internal.Mimetypes: can't find referenced class org.apache.commons.logging.LogFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.services.s3.internal.Mimetypes: can't find referenced class org.apache.commons.logging.LogFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.services.s3.internal.ObjectExpirationHeaderHandler: can't find referenced class org.apache.commons.logging.LogFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.services.s3.internal.ObjectExpirationHeaderHandler: can't find referenced class org.apache.commons.logging.LogFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.services.s3.internal.ObjectRestoreHeaderHandler: can't find referenced class org.apache.commons.logging.LogFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.services.s3.internal.ObjectRestoreHeaderHandler: can't find referenced class org.apache.commons.logging.LogFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.services.s3.internal.RepeatableFileInputStream: can't find referenced class org.apache.commons.logging.LogFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.services.s3.internal.RepeatableFileInputStream: can't find referenced class org.apache.commons.logging.LogFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.services.s3.internal.S3ErrorResponseHandler: can't find referenced class org.apache.commons.logging.LogFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.services.s3.internal.S3ErrorResponseHandler: can't find referenced class org.apache.commons.logging.LogFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.services.s3.internal.S3Signer: can't find referenced class org.apache.commons.logging.LogFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.services.s3.internal.S3Signer: can't find referenced class org.apache.commons.logging.LogFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.services.s3.internal.S3XmlResponseHandler: can't find referenced class org.apache.commons.logging.LogFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.services.s3.internal.S3XmlResponseHandler: can't find referenced class org.apache.commons.logging.LogFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.services.s3.internal.ServiceUtils: can't find referenced class org.apache.commons.logging.LogFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.services.s3.internal.ServiceUtils: can't find referenced class org.apache.commons.logging.LogFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.services.s3.internal.crypto.CryptoRuntime: can't find referenced class org.apache.commons.logging.LogFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.services.s3.internal.crypto.CryptoRuntime: can't find referenced class org.apache.commons.logging.LogFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.services.s3.internal.crypto.S3CryptoModuleBase: can't find referenced class org.apache.commons.logging.LogFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.services.s3.internal.crypto.S3CryptoModuleBase: can't find referenced class org.apache.commons.logging.LogFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.services.s3.model.S3ObjectInputStream: can't find referenced class org.apache.commons.logging.LogFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.services.s3.model.S3ObjectInputStream: can't find referenced class org.apache.commons.logging.LogFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.services.s3.model.transform.XmlResponsesSaxParser: can't find referenced class org.apache.commons.logging.LogFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.services.s3.model.transform.XmlResponsesSaxParser: can't find referenced class org.apache.commons.logging.LogFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.transform.SimpleTypeStaxUnmarshallers: can't find referenced class org.apache.commons.logging.LogFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.transform.SimpleTypeStaxUnmarshallers: can't find referenced class org.apache.commons.logging.LogFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.util.AWSRequestMetricsFullSupport: can't find referenced class org.apache.commons.logging.LogFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.util.AWSRequestMetricsFullSupport: can't find referenced class org.apache.commons.logging.LogFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.util.AWSRequestMetricsFullSupport: can't find referenced class org.apache.commons.logging.LogFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.util.AwsHostNameUtils: can't find referenced class org.apache.commons.logging.LogFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.util.AwsHostNameUtils: can't find referenced class org.apache.commons.logging.LogFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.util.Md5Utils: can't find referenced class org.apache.commons.logging.LogFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.util.Md5Utils: can't find referenced class org.apache.commons.logging.LogFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.util.Throwables: can't find referenced class org.apache.commons.logging.LogFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.util.Throwables: can't find referenced class org.apache.commons.logging.LogFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.util.TimingInfoFullSupport: can't find referenced class org.apache.commons.logging.LogFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.util.TimingInfoFullSupport: can't find referenced class org.apache.commons.logging.LogFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.util.VersionInfoUtils: can't find referenced class org.apache.commons.logging.LogFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.util.VersionInfoUtils: can't find referenced class org.apache.commons.logging.LogFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.util.XpathUtils: can't find referenced class org.apache.commons.logging.LogFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.util.XpathUtils: can't find referenced class org.apache.commons.logging.LogFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.util.json.JacksonFactory: can't find referenced class com.fasterxml.jackson.core.JsonFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.util.json.JacksonFactory: can't find referenced class com.fasterxml.jackson.core.JsonFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.util.json.JacksonFactory: can't find referenced class com.fasterxml.jackson.core.JsonToken
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.util.json.JacksonFactory: can't find referenced class com.fasterxml.jackson.core.JsonToken
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.util.json.JacksonFactory: can't find referenced class com.fasterxml.jackson.core.JsonFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.util.json.JacksonFactory: can't find referenced class com.fasterxml.jackson.core.JsonToken
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.util.json.JacksonFactory: can't find referenced class com.fasterxml.jackson.core.JsonToken
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.util.json.JacksonFactory: can't find referenced class com.fasterxml.jackson.core.JsonToken
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.util.json.JacksonFactory: can't find referenced class com.fasterxml.jackson.core.JsonToken
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.util.json.JacksonFactory$1: can't find referenced class com.fasterxml.jackson.core.JsonToken
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.util.json.JacksonFactory$1: can't find referenced class com.fasterxml.jackson.core.JsonToken
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.util.json.JacksonFactory$1: can't find referenced class com.fasterxml.jackson.core.JsonToken
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.util.json.JacksonFactory$1: can't find referenced class com.fasterxml.jackson.core.JsonToken
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.util.json.JacksonFactory$1: can't find referenced class com.fasterxml.jackson.core.JsonToken
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.util.json.JacksonFactory$1: can't find referenced class com.fasterxml.jackson.core.JsonToken
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.util.json.JacksonFactory$1: can't find referenced class com.fasterxml.jackson.core.JsonToken
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.util.json.JacksonFactory$1: can't find referenced class com.fasterxml.jackson.core.JsonToken
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.util.json.JacksonFactory$1: can't find referenced class com.fasterxml.jackson.core.JsonToken
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.util.json.JacksonFactory$1: can't find referenced class com.fasterxml.jackson.core.JsonToken
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.util.json.JacksonFactory$1: can't find referenced class com.fasterxml.jackson.core.JsonToken
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.util.json.JacksonFactory$1: can't find referenced class com.fasterxml.jackson.core.JsonToken
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.util.json.JacksonFactory$1: can't find referenced class com.fasterxml.jackson.core.JsonToken
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.util.json.JacksonFactory$1: can't find referenced class com.fasterxml.jackson.core.JsonToken
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.util.json.JacksonFactory$JacksonReader: can't find referenced class com.fasterxml.jackson.core.JsonFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.util.json.JacksonFactory$JacksonReader: can't find referenced class com.fasterxml.jackson.core.JsonFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.util.json.JacksonFactory$JacksonReader: can't find referenced class com.fasterxml.jackson.core.JsonToken
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.util.json.JacksonFactory$JacksonReader: can't find referenced class com.fasterxml.jackson.core.JsonToken
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.util.json.JacksonFactory$JacksonReader: can't find referenced class com.fasterxml.jackson.core.JsonToken
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.util.json.JacksonFactory$JacksonReader: can't find referenced class com.fasterxml.jackson.core.JsonToken
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.util.json.JacksonFactory$JacksonReader: can't find referenced class com.fasterxml.jackson.core.JsonToken
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.util.json.JacksonFactory$JacksonReader: can't find referenced class com.fasterxml.jackson.core.JsonToken
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.util.json.JacksonFactory$JacksonReader: can't find referenced class com.fasterxml.jackson.core.JsonParser
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.util.json.JacksonFactory$JacksonReader: can't find referenced class com.fasterxml.jackson.core.JsonParser
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.util.json.JacksonFactory$JacksonReader: can't find referenced class com.fasterxml.jackson.core.JsonToken
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.util.json.JacksonFactory$JacksonReader: can't find referenced class com.fasterxml.jackson.core.JsonParser
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.util.json.JacksonFactory$JacksonReader: can't find referenced class com.fasterxml.jackson.core.JsonParser
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.util.json.JacksonFactory$JacksonReader: can't find referenced class com.fasterxml.jackson.core.JsonParser
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.util.json.JacksonFactory$JacksonReader: can't find referenced class com.fasterxml.jackson.core.JsonParser
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.util.json.JacksonFactory$JacksonReader: can't find referenced class com.fasterxml.jackson.core.JsonToken
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.util.json.JacksonFactory$JacksonReader: can't find referenced class com.fasterxml.jackson.core.JsonFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.util.json.JacksonFactory$JacksonReader: can't find referenced class com.fasterxml.jackson.core.JsonFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.util.json.JacksonFactory$JacksonReader: can't find referenced class com.fasterxml.jackson.core.JsonToken
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.util.json.JacksonFactory$JacksonReader: can't find referenced class com.fasterxml.jackson.core.JsonToken
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.util.json.JacksonFactory$JacksonWriter: can't find referenced class com.fasterxml.jackson.core.JsonFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.util.json.JacksonFactory$JacksonWriter: can't find referenced class com.fasterxml.jackson.core.JsonFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.util.json.JacksonFactory$JacksonWriter: can't find referenced class com.fasterxml.jackson.core.JsonGenerator
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.util.json.JacksonFactory$JacksonWriter: can't find referenced class com.fasterxml.jackson.core.JsonGenerator
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.util.json.JacksonFactory$JacksonWriter: can't find referenced class com.fasterxml.jackson.core.JsonGenerator
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.util.json.JacksonFactory$JacksonWriter: can't find referenced class com.fasterxml.jackson.core.JsonGenerator
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.util.json.JacksonFactory$JacksonWriter: can't find referenced class com.fasterxml.jackson.core.JsonGenerator
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.util.json.JacksonFactory$JacksonWriter: can't find referenced class com.fasterxml.jackson.core.JsonGenerator
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.util.json.JacksonFactory$JacksonWriter: can't find referenced class com.fasterxml.jackson.core.JsonGenerator
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.util.json.JacksonFactory$JacksonWriter: can't find referenced class com.fasterxml.jackson.core.JsonGenerator
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.util.json.JacksonFactory$JacksonWriter: can't find referenced class com.fasterxml.jackson.core.JsonGenerator
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.util.json.JacksonFactory$JacksonWriter: can't find referenced class com.fasterxml.jackson.core.JsonGenerator
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.util.json.JacksonFactory$JacksonWriter: can't find referenced class com.fasterxml.jackson.core.JsonGenerator
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.util.json.JacksonFactory$JacksonWriter: can't find referenced class com.fasterxml.jackson.core.JsonGenerator
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.util.json.JacksonFactory$JacksonWriter: can't find referenced class com.fasterxml.jackson.core.JsonGenerator
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.util.json.JacksonFactory$JacksonWriter: can't find referenced class com.fasterxml.jackson.core.JsonGenerator
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.util.json.JacksonFactory$JacksonWriter: can't find referenced class com.fasterxml.jackson.core.JsonGenerator
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.util.json.JacksonFactory$JacksonWriter: can't find referenced class com.fasterxml.jackson.core.JsonFactory
[2015-12-30 17:49:46 - TheGrooveBos] Warning: com.amazonaws.util.json.JacksonFactory$JacksonWriter: can't find referenced class com.fasterxml.jackson.core.JsonFactory
[2015-12-30 17:49:46 - TheGrooveBos]       You should check if you need to specify additional program jars.
[2015-12-30 17:49:46 - TheGrooveBos] Warning: there were 164 unresolved references to classes or interfaces.
[2015-12-30 17:49:46 - TheGrooveBos]          You may need to specify additional library jars (using '-libraryjars').
[2015-12-30 17:49:46 - TheGrooveBos] java.io.IOException: Please correct the above warnings first.
[2015-12-30 17:49:46 - TheGrooveBos]    at proguard.Initializer.execute(Initializer.java:321)
[2015-12-30 17:49:46 - TheGrooveBos]    at proguard.ProGuard.initialize(ProGuard.java:211)
[2015-12-30 17:49:46 - TheGrooveBos]    at proguard.ProGuard.execute(ProGuard.java:86)
[2015-12-30 17:49:46 - TheGrooveBos]    at proguard.ProGuard.main(ProGuard.java:492)

Proguard file

   #-keepclassmembers class fqcn.of.javascript.interface.for.webview {
    #   public *;
    -keep class com.google.android.gms.** { *; }
    -dontwarn com.google.android.gms.**
    -dontwarn com.squareup.picasso.**
    -keep class com.squareup.okhttp.** { *; }
    -keep interface com.squareup.okhttp.** { *; }
    -dontwarn com.squareup.okhttp.**
    -dontwarn rx.**
    -dontwarn retrofit.**
    -dontwarn okio.**
    -keepattributes Signature
    keep class org.apache.commons.logging.**               { *; }
-keep class com.amazonaws.services.sqs.QueueUrlHandler  { *; }
-keep class com.amazonaws.javax.xml.transform.sax.*     { public *; }
-keep class com.amazonaws.javax.xml.stream.**           { *; }
-keep class com.amazonaws.services.**.model.*Exception* { *; }
-keep class org.codehaus.**                             { *; }
-keepattributes Signature,*Annotation*

-dontwarn javax.xml.stream.events.**
-dontwarn org.codehaus.jackson.**
-dontwarn org.apache.commons.logging.impl.**
-dontwarn org.apache.http.conn.scheme.**
    -keepattributes Exceptions
    -keep class retrofit.** { *; }
    -keepclasseswithmembers class * {
        @retrofit.http.* <methods>;
    }
    #}

**Comment by fosterzhang** [comment]
Please refer to https://github.com/aws/aws-sdk-android/blob/master/Proguard.md

**Comment by achinverma** [comment]
thanks @fosterzhang
