### ISSUE TITLE
Exception uploading image to S3

### ISSUE THREAD

**Issue by seikomg** [awslabs/aws-sdk-android-samples#52]
Hi,

I have recently started managing images on S3 through Android app. I keep getting this exception when trying to upload an image. I get a similar exception when deleting images on S3 (have opened issue #51)

Unable to execute HTTP request: null
                                                                         java.io.EOFException
                                                                             at libcore.io.Streams.readAsciiLine(Streams.java:203)
                                                                             at libcore.net.http.HttpEngine.readResponseHeaders(HttpEngine.java:560)
                                                                             at libcore.net.http.HttpEngine.readResponse(HttpEngine.java:813)
                                                                             at libcore.net.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:274)
                                                                             at libcore.net.http.HttpURLConnectionImpl.getResponseMessage(HttpURLConnectionImpl.java:482)
                                                                             at libcore.net.http.HttpsURLConnectionImpl.getResponseMessage(HttpsURLConnectionImpl.java:139)
                                                                             at com.amazonaws.http.UrlHttpClient.createHttpResponse(UrlHttpClient.java:72)
                                                                             at com.amazonaws.http.UrlHttpClient.execute(UrlHttpClient.java:66)
                                                                             at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:360)
                                                                             at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:199)
                                                                             at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.invoke(AmazonCognitoIdentityClient.java:533)
                                                                             at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.getId(AmazonCognitoIdentityClient.java:344)
                                                                             at com.amazonaws.auth.AWSAbstractCognitoIdentityProvider.getIdentityId(AWSAbstractCognitoIdentityProvider.java:172)
                                                                             at com.amazonaws.auth.AWSEnhancedCognitoIdentityProvider.refresh(AWSEnhancedCognitoIdentityProvider.java:76)
                                                                             at com.amazonaws.auth.CognitoCredentialsProvider.startSession(CognitoCredentialsProvider.java:537)
                                                                             at com.amazonaws.auth.CognitoCredentialsProvider.getCredentials(CognitoCredentialsProvider.java:370)
                                                                             at com.amazonaws.auth.CognitoCredentialsProvider.getCredentials(CognitoCredentialsProvider.java:44)
                                                                             at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4215)
                                                                             at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1628)
                                                                             at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.uploadSinglePartAndWaitForCompletion(UploadTask.java:195)
                                                                             at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:79)
                                                                             at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:44)

**Comment by seikomg** [comment]
aws-sdk-core - 2.2.14
aws-sdk-s3 - 2.2.14

devices: samsung galaxy s3 (model # SGH-T999) android 4.1.1, 
samsung tablet (model # GT-P3113), android 4.2.2

I appreciate your help!

**Comment by fosterzhang** [comment]
@seikomg Have you tried your app on later devices, say Android 4.4 KitKat API level 19 or later? Does the sample app work ok? What's your S3 region?

**Comment by seikomg** [comment]
I haven't tried on other devices yet. I also have not run the sample app as is. My S3 region is US-West (Oregon). I will run the sample app and see what happens.

**Comment by seikomg** [comment]
I ran the S3TransferUtilitySample, it did not throw the exception, but it also did not work at all times. The image upload would hang sometimes, with no exceptions on either WAITING or IN_PROGRESS state. The same code in my application worked a few times I tried. I also switched to US EAST region. I now suspect my issue to be because I tried to upload multiple files as an RxJava subscription . I noticed there is no batchUpload for android. What is the best way to upload multiple files?

**Comment by fosterzhang** [comment]
@seikomg WAITING should eventually change to IN_PROGRESS. There might be a bug with the listener where events aren't fire when socket timeout occurs. I am still investigating. Please do the transfer with a better network and/or increase socket timeout via ClientConfiguration.

There isn't a batchUpload, but you can achieve a similar result by queuing up lots of uploads via `TransferUtility.upload`.

Sorry that I am not familiar with RxJava, so I can't help you on this matter.

**Comment by seikomg** [comment]
@fosterzhang , thank you for your quick response. I think I was getting the upload exception because I was trying to upload multiple files using RxJava and I wasn't using the RxJava subscription correctly. I have fixed that, but there is a new problem. deleteObject is still throwing the same error. And the funny thing is the image is actually being deleted off of S3! And even more confusing is once I get this error (on delete), any subsequent uploads also throw this error, but uploads images successfully in the background!! I am at a complete loss :)

I am also unable to understand why the try/catch block (in case of deleteObject()), onError() in case of TransferUtility or RxJava error handler) is not able to catch this exception.

**Comment by seikomg** [comment]
@fosterzhang, is there anything else that I can try?

**Comment by fosterzhang** [comment]
@seikomg would you please share your code to reproduce the issue?

**Comment by seikomg** [comment]
@fosterzhang, I am actually using RxJava in my code now, but I get the same error if I run the deleteObject() method in an async task. Pasting the async task code out here. The exception is never caught. Hope this helps. Please let me know if you need any more information.

Async Task-
public class DeleteS3FileAsyncTask extends AsyncTask<String, Integer, Boolean>{

    private Context context;

    public DeleteS3FileAsyncTask(Context context){
        this.context = context;
    }

    @Override
    protected Boolean doInBackground(String... strings) {

        AWSHelper helper = new AWSHelper(context);
        return helper.deleteFile(strings[0]);
    }

    protected void onPostExecute(Boolean result){
        BusProvider.postOnMain(result);
    }
}

Here is the helper class-
public class AWSHelper {

private AmazonS3Client getS3Client() {
        AWSCredentialsProvider credentialsProvider = new CognitoCredentialsProvider("myId", Regions.US_EAST_1);
        return new AmazonS3Client(credentialsProvider);
    }

  public boolean deleteFile(String key) {
        boolean success = true;
        AmazonS3Client client = getS3Client();
        try {
            if(client != null && !TextUtils.isEmpty(key)){
                     client.deleteObject(AWS_BUCKET, key);
            }
        } catch (Exception e) {
            success = false;
        }

        return success;
    }
}

**Comment by fosterzhang** [comment]
@seikomg What's the format of the bucket name? Does it contain dot '.' ?

**Comment by seikomg** [comment]
No special characters, at this point, its just a simple string

**Comment by fosterzhang** [comment]
@seikomg Which region is your bucket? Do you see exception in the stacktrace? FYI, AmazonS3 throws AmazonClientException and AmazonServiceException which are both RuntimeException.

**Comment by seikomg** [comment]
@fosterzhang Hmm, if I explicitly catch AmazonClientException, I don't see it thrown in the stack trace. I am not sure I understand what is going on, but since it has been fixed for now, I will go ahead and close this issue. Will re-open if need be. Thanks for your help @fosterzhang
