### ISSUE TITLE
com.amazonaws.AmazonClientException: Unable to verify integrity of data download

### ISSUE THREAD

**Issue by FabioConsonni** [awslabs/aws-sdk-android-samples#62]
Hi all.

I used the S3 TransferUtility to test my bucket. My bucket contains subfolders with images in jpeg format. The size of each file is more or less 100 kb.

Everything is working well in all condition Wifi and almost all mobile network.
Only on one of the major mobile operator in my country (Italy) I have a problem.
On several files, not all files, when I download the file through the Transfer Utility Download Task, I got this error:

com.amazonaws.AmazonClientException: Unable to verify integrity of data download.  Client calculated content hash didn't match hash calculated by Amazon S3.  The data may be corrupt.
                                                                                 at com.amazonaws.services.s3.internal.DigestValidationInputStream.validateMD5Digest(DigestValidationInputStream.java:80)
                                                                                 at com.amazonaws.services.s3.internal.DigestValidationInputStream.read(DigestValidationInputStream.java:62)
                                                                                 at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:73)
                                                                                 at java.io.InputStream.read(InputStream.java:162)
                                                                                 at com.amazonaws.mobileconnectors.s3.transferutility.DownloadTask.saveToFile(DownloadTask.java:146)
                                                                                 at com.amazonaws.mobileconnectors.s3.transferutility.DownloadTask.call(DownloadTask.java:103)
                                                                                 at com.amazonaws.mobileconnectors.s3.transferutility.DownloadTask.call(DownloadTask.java:39)
                                                                                 at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                 at java.lang.Thread.run(Thread.java:818)

The error is repetitive, 
It is strange that almost all times the files are correctly donwloaded but I got the error.

Can someone give me an explanation of how is it possible to get this error on a particular mobile operator?

Is it possible to disable this automatic check? In my opition for my application I could not use this feature.

Thanks to all, 
Fabio.

**Comment by fosterzhang** [comment]
@FabioConsonni S3 client checks content MD5 against its source's eTag. If for some reason, this validation fails, the downloaded data may be bogus. To skip the MD5 check, you can set system property `com.amazonaws.services.s3.disableGetObjectMD5Validation`.

**Comment by FabioConsonni** [comment]
@fosterzhang 
Thank you so much for your help!
It works very well.

Kindly I would like to understand better the situation.
When you say "the downloaded data may be bogus", it is not clear for me, because if I check after the download, I have the file and I can open the image correctly.

Also it is very strange that I have this problem only on a specific mobile network operator.
On all others mobile operator or via WiFi with cabled network operator I don't have this problem.

My suppose is that the specific mobile operator modify something in the stream during the download. 
Do you think maybe possible?

In your opinion, what could I check to understand what happen?
I know that this is not a your problem, but I saw in the past this problem in a post and it was closed because it was not possible to reproduce it.
Now if you can guide me, I can try to make some tests and maybe, I don't know give an help to solve it, because it is not a good idea to remove this check.

In any case, thanks in advance for your help!

Fabio.

**Comment by fosterzhang** [comment]
@FabioConsonni some wild guesses:
- the ISP alters ETag header for some reason.
- the SDK retries due to bad network connection and causes MD5 incorrectly computed.
- when uploading the file, someone overwrites the ETag value.
- some unknown bug in the SDK

Would you please get the file from the device and compute its MD5? It should match the value in S3.
