### ISSUE TITLE
Unique constraint error

### ISSUE THREAD

**Issue by jukka-palomaki** [awslabs/aws-sdk-android-samples#79]
Have others seen this sometimes in YourUserPoolsDemo when waiting for long time and then logging in again. First time it gives "Unique Constraint Error" and second time sign in works. Can this be related to my gradle dependencies? I am waiting for fix in com.amazonaws:aws-android-sdk-cognitoidentityprovider 2.3.0 related to one Threading/Looper error (there is a separate issue about this). That's why I am using 2.2.18 now.

```
compile('com.amazonaws:aws-android-sdk-cognito:2.2.18')
compile('com.amazonaws:aws-android-sdk-cognitoidentityprovider:2.2.18')
compile('com.amazonaws:aws-android-sdk-core:2.3.0')
compile('com.amazonaws:aws-android-sdk-ddb:2.3.0')
compile('com.amazonaws:aws-android-sdk-ddb-mapper:2.3.0')
compile('com.amazonaws:aws-android-sdk-lambda:2.3.0')
compile('com.amazonaws:aws-android-sdk-mobileanalytics:2.3.0')
compile('com.amazonaws:aws-android-sdk-s3:2.3.0')
compile('com.amazonaws:aws-android-sdk-sns:2.3.0')
```

**Comment by jbailey2010** [comment]
To help investigate further, can you post an entire stack trace from the failure when it occurs? It'll help us narrow down what could be happening.

**Comment by jukka-palomaki** [comment]
`09-01 10:01:43.517 6879-7985/com.xxx.yyy E/SQLiteLog: (2067) abort at 37 in [UPDATE datasets SET identity_id = 'us-east-1:edd9df02-9730-4c33-82a7-8c5d8225acb3' WHERE identity_id = ?]: UNIQUE constraint failed: datasets.identity_id, datasets.dataset_name
09-01 10:01:43.527 6879-7985/com.xxx.yyy D/IdentityManager: SignInResultsAdapter.onCognitoError()
                                                                        android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: datasets.identity_id, datasets.dataset_name (code 2067)
                                                                            at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
                                                                            at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:904)
                                                                            at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:754)
                                                                            at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:64)
                                                                            at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1814)
                                                                            at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1793)
                                                                            at com.amazonaws.mobileconnectors.cognito.internal.storage.SQLiteLocalStorage.changeIdentityId(SQLiteLocalStorage.java:741)
                                                                            at com.amazonaws.mobileconnectors.cognito.CognitoSyncManager$1.identityChanged(CognitoSyncManager.java:135)
                                                                            at com.amazonaws.auth.AWSAbstractCognitoIdentityProvider.identityChanged(AWSAbstractCognitoIdentityProvider.java:260)
                                                                            at com.amazonaws.auth.AWSAbstractCognitoIdentityProvider.getIdentityId(AWSAbstractCognitoIdentityProvider.java:175)
                                                                            at com.amazonaws.auth.AWSAbstractCognitoIdentityProvider.refresh(AWSAbstractCognitoIdentityProvider.java:313)
                                                                            at com.amazonaws.auth.AWSBasicCognitoIdentityProvider.refresh(AWSBasicCognitoIdentityProvider.java:77)
                                                                            at com.amazonaws.mobile.user.IdentityManager$AWSRefreshingCognitoIdentityProvider.refresh(IdentityManager.java:110)
                                                                            at com.amazonaws.auth.CognitoCredentialsProvider.startSession(CognitoCredentialsProvider.java:561)
                                                                            at com.amazonaws.auth.CognitoCredentialsProvider.refresh(CognitoCredentialsProvider.java:527)
                                                                            at com.amazonaws.auth.CognitoCachingCredentialsProvider.refresh(CognitoCachingCredentialsProvider.java:463)
                                                                            at com.amazonaws.mobile.user.IdentityManager.refreshCredentialWithLogins(IdentityManager.java:399)
                                                                            at com.amazonaws.mobile.user.IdentityManager.access$200(IdentityManager.java:38)
                                                                            at com.amazonaws.mobile.user.IdentityManager$2.run(IdentityManager.java:418)
                                                                            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                                            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                            at java.lang.Thread.run(Thread.java:818)
09-01 10:01:43.527 6879-6879/com.xxx.yyy D/XXX-APP: [SignInActivity]: JAP SignInResultsHandler.onError started
09-01 10:01:43.537 6879-6879/com.xxx.yyy E/XXX-APP: [SignInActivity]: User Sign-in failed for Nuviz : UNIQUE constraint failed: datasets.identity_id, datasets.dataset_name (code 2067)
                                                                android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: datasets.identity_id, datasets.dataset_name (code 2067)
                                                                    at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
                                                                    at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:904)
                                                                    at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:754)
                                                                    at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:64)
                                                                    at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1814)
                                                                    at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1793)
                                                                    at com.amazonaws.mobileconnectors.cognito.internal.storage.SQLiteLocalStorage.changeIdentityId(SQLiteLocalStorage.java:741)
                                                                    at com.amazonaws.mobileconnectors.cognito.CognitoSyncManager$1.identityChanged(CognitoSyncManager.java:135)
                                                                    at com.amazonaws.auth.AWSAbstractCognitoIdentityProvider.identityChanged(AWSAbstractCognitoIdentityProvider.java:260)
                                                                    at com.amazonaws.auth.AWSAbstractCognitoIdentityProvider.getIdentityId(AWSAbstractCognitoIdentityProvider.java:175)
                                                                    at com.amazonaws.auth.AWSAbstractCognitoIdentityProvider.refresh(AWSAbstractCognitoIdentityProvider.java:313)
                                                                    at com.amazonaws.auth.AWSBasicCognitoIdentityProvider.refresh(AWSBasicCognitoIdentityProvider.java:77)
                                                                    at com.amazonaws.mobile.user.IdentityManager$AWSRefreshingCognitoIdentityProvider.refresh(IdentityManager.java:110)
                                                                    at com.amazonaws.auth.CognitoCredentialsProvider.startSession(CognitoCredentialsProvider.java:561)
                                                                    at com.amazonaws.auth.CognitoCredentialsProvider.refresh(CognitoCredentialsProvider.java:527)
                                                                    at com.amazonaws.auth.CognitoCachingCredentialsProvider.refresh(CognitoCachingCredentialsProvider.java:463)
                                                                    at com.amazonaws.mobile.user.IdentityManager.refreshCredentialWithLogins(IdentityManager.java:399)
                                                                    at com.amazonaws.mobile.user.IdentityManager.access$200(IdentityManager.java:38)
                                                                    at com.amazonaws.mobile.user.IdentityManager$2.run(IdentityManager.java:418)
                                                                    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                                    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                    at java.lang.Thread.run(Thread.java:818)
`

**Comment by jbailey2010** [comment]
Ah, so it's the sync data that's causing trouble, not user pools stuff. This is a known (tricky) issue with the SDK. The recommended workaround is to call SyncManager.wipeData() when you log off from a user, which will clear all the records that are colliding with new ones.

**Comment by jukka-palomaki** [comment]
Thanks!!

**Comment by aneeshjoshi** [comment]
Calling SyncManager.wipeData() will cause the loss of any unsynchronized data. This is hardly an acceptable solution for this error being thrown when attempting to refresh token.

**Comment by atnegrete** [comment]
Agreed, this is an awful solution. Anyone have any better ones?

**Comment by dkobia** [comment]
The solution above from @aneeshjoshi is unfortunately an awful solution. It does work in the interim but presents real problems when you start to store more stuff in Cognito Sync like user preferences. `SyncManager.wipeData()` wipes those preferences away.

**Comment by aneeshjoshi** [comment]
Based on the last year of troubleshooting this, my current hypothesis is that the problem arises when the identity token has expired (we are using AWS Cognito User Pool as our Auth Provider). The dataset becomes anonymized when the identity changes. When the token eventually refreshes there's some form of a "merge" conflict between the user's actual dataset and the anonymous dataset leading to this exception. Unfortunately I haven't been able to capture this in the wild and thus is simply a guess. 

We think we were able to alleviate this problem by carefully managing the token refresh process. All of this is inelegant though. Ideally the SyncManager (& other AWS sdk libraries) would manage the id token refresh internally rather than needing to have the logins being set by the user manually.

**Comment by dkobia** [comment]
@karthiksaligrama does the new AppSync replace Cognito Sync and rectify all these issues?
